### ISSUE TITLE
possible insert eps file into

### ISSUE THREAD

**Issue by ghiewa** [jung-kurt/gofpdf#100]
like
## pdf.EPS("D:/IDP/DoneNL/QQ876L_1.Eps", 10, 6, 30, 0, false, "", 0, "")
or something else

```
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetHeaderFunc(func() {
		pdf.EPS("D:/IDP/DoneNL/QQ876L_1.Eps", 10, 6, 30, 0, false, "", 0, "")
		pdf.SetY(5)
		pdf.SetFont("Arial", "B", 15)
		pdf.Cell(80, 0, "")
		pdf.CellFormat(30, 10, "Title", "1", 0, "C", false, 0, "")
		pdf.Ln(20)
	})
```

**Comment by jung-kurt** [comment]
Reading, parsing and rendering an EPS file (Adobe vector graphics format) is pretty far out of fpdf's scope. Your best bet may be to convert the document to a PNG file first, then include it using the [Image()](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.Image) method.

**Comment by Gys** [comment]
@jung-kurt I have a question that might relate to this closed issue. That is why I comment here.

I am looking for ways to add some smaller pdf's inside another pdf. Its to put commercial ads (small pdf files) on one magazine's page. It might be a similar use case as @ghiewa was thinking of. Its something that for example Adobe Indesign or altsoft xml2pdf can do.

Assuming the exact rendered size of the to be embedded pdf or eps is known, wouldn't it be possible to 'just' define that space inside a pdf and then 'simply' copy the pdf/eps contents into that space ?

**Comment by jung-kurt** [comment]
Embedding an EPS file is pretty simplistic -- it is simply included as a static image, something gofdpf already supports. If you have a way to convert the smaller PDF ads into images, that would likely be your best bet. However, you would lose features like copy-and-pasting text, hyperlinks, etc.

You may want to looking into [templating](https://github.com/jung-kurt/gofpdf/pull/33) if you create the smaller PDFs yourself.

Also, if you have access to the command line for post-processing, the [PDFtk](https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/) toolkit handles all kinds of document manipulation.

Unfortunately, there is more to embedding than simply setting aside space. The internal catalogs of resources with offsets have to be managed. I suspect Indesign merges the resources of the included PDF right into the main PDF's resources but I'm not sure.

If someone could implement the direct embedding of PDFs, it would make a great a feature.

**Comment by marcusatbang** [comment]
I'm sorry I never finished that. Even working from the base of FPDI, there's a lot of work involved in not just parsing and transferring PDF pages but also working resources into internal catalogues - and that's before you start on re-subsetting fonts. If somebody wants to pay me to not work for a few months (and persuade my boss he can do without me), I'd be glad to finish it.

More realistically, if somebody wants to take the work I've done so far and run with it, it's here:
https://github.com/marcusatbang/gofpdf/tree/parse-pdf

**Comment by Gys** [comment]
@jung-kurt Converting a pdf into a rasterized image means setting the output resolution plus increasing the file size significantly. However, a pdf can also easily be converted into an EPS.

So if embedding an EPS is pretty simplistic, do you mean embedding the EPS preview (an EPS generally has a lower res preview image part) ? Or do you really mean the postscript part ? Because if the postscript part is included, then embedding a pdf that way (by converting to eps first) would be great.

**Comment by jung-kurt** [comment]
@marcusatbang It would be great if someone can continue from the good work you've started. I can offer you 100% of the proceeds from gofpdf :-)

@Gys My thoughts were to embed the rasterized image. Clearly this is unacceptable for anything except the case in which the PDF to be embedded is composed only of images itself.
