### ISSUE TITLE
New line in MultiCell() text string.

### ISSUE THREAD

**Issue by NCSantos** [jung-kurt/gofpdf#105]
Hi,

Is it possible to insert a string with new line in MultiCell()?
I want a new line even if the line before is not longer than the width of the MultiCell().

Thanks.

**Comment by jung-kurt** [comment]
Yes. The [`ExampleFpdf_MultiCell()`](https://github.com/jung-kurt/gofpdf/blob/6ac7d2caee89cdfdb4f6c273a88d1173d234c21b/fpdf_test.go#L142-L216) function shows how a text file which includes newlines is rendered with a single call to `MultiCell()`.

**Comment by NCSantos** [comment]
I missread the MultiCell() arg h, it's "line height".
But this doesn't help me.
I'm trying to draw labels for letters, I need the text in the left and middle.
It has, atleast, name, address, postal code.
Any advice?

**Comment by jung-kurt** [comment]
Fixed width font, maybe?

**Comment by NCSantos** [comment]
Sorry but can't think of a way fixed width font can help.
Maybe I explained it wrong.

I have a labels sheet of 3 by 8 labels, I need to write the name, address and postal code of our members on each label. The text has to be left and middle justifyed on its label.

Is there a good way to do this?

Thanks.

**Comment by jung-kurt** [comment]
Yes. 

* The parameters you want to know will be the left and right page margins, vertical and horizontal gaps between labels, label width and height, etc.
* Make a nested loop, say rows in the outer loop, columns in the inner loop, just as in the [polygon example](https://github.com/jung-kurt/gofpdf/blob/6ac7d2caee89cdfdb4f6c273a88d11Z73d234c21b/fpdf_test.go#L1351-L1361). 
* Use [`Cell()`](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.CellFormat), not `MultiCell()`.

**Comment by NCSantos** [comment]
Thanks. Yes I think thats the best solution.

Now I'm having another problem, why does this prints the text with 2 different sizes?

`
pdf := gofpdf.New("P", "pt", "A4", "")
pdf.AddPage()
pdf.SetFont("Arial", "", 10)
pdf.SetAutoPageBreak(false, 1)

pdf.SetXY(10, 10)
pdf.Cell(0, 0, "test")
pdf.SetFontSize(10)
pdf.SetXY(10, 30)
pdf.Cell(0, 0, "test")

err := pdf.Output(w)
if err != nil {
	fmt.Println("Error: ", err)
} else {
	fmt.Println("OK")
}
defer pdf.Close()
`

Thanks.

**Comment by jung-kurt** [comment]
I just ran your example and am not getting two different font sizes.

**Comment by NCSantos** [comment]
Yes, you were rigth, it was an issue in my code.

Thanks for your help.

**Comment by jung-kurt** [comment]
Thanks, @NCSantos -- I'll close this issue. Reopen it if you encounter more issues.
