### ISSUE TITLE
I can not use Arabic language in pdf

### ISSUE THREAD

**Issue by AttSee** [jung-kurt/gofpdf#107]
hi Great work but
I want to use the library gofpdf
But it does not support the Arabic 
I want solve the problem

I try this but it does not work

package main

import (
	"github.com/jung-kurt/gofpdf"
	"fmt"
	"os"
)

func main() {
	pwd, err := os.Getwd()
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
	pdf := gofpdf.New("P", "mm", "A4", pwd + "/font/")
	pdf.AddFont("Helvetica", "", "helvetica_1251.json")
	pdf.AddPage()
	pdf.SetFont("Helvetica", "", 16)
	tr := pdf.UnicodeTranslatorFromDescriptor("cp1251")
	pdf.Cell(15, 50, tr("الايام السبع"))
	pdf.OutputFileAndClose("test.pdf")
}

**Comment by jung-kurt** [comment]
Unfortunately, gofdpf has very poor support for Arabic. The closest code page is [864](https://en.wikipedia.org/wiki/Code_page_864). You would have to manually construct a map file for it. (If you do this, I'd be happy to include it in this package.) But even if you succeeded with that and were able to generate a JSON font descriptor file, gofdpf regrettably does not support right-to-left rendering. I hope these deficiencies can be remedied some day.

**Comment by AttSee** [comment]
Thanks for your reply I tried to convert the file ttf to JSON
by this site https://gero3.github.io/facetype.js/ 
font with json 
[traditional-arabic6.zip](https://github.com/jung-kurt/gofpdf/files/896364/traditional-arabic6.zip)

But it worked with  gopdf  library
https://github.com/signintech/gopdf/issues/50

he use  :

func reverseString(s string) string {
	runes := []rune(s)
	for i, j := 0, len(runes)-1; i < j; i, j = i+1, j-1 {
		runes[i], runes[j] = runes[j], runes[i]
	}
	return string(runes)
}


and "github.com/01walid/goarabic"

**Comment by jung-kurt** [comment]
Thanks, @AttSee, for your remarks and the link to the Arabic font. That font has 607 characters and, unfortunately, gofdpf is restricted to 256. Until we can add UTF-8 support to gofdpf, I think you will be better served with gopdf.

The reverseString routine used with right-justification is a good technique to know.

Good luck!
