### ISSUE TITLE
does this library have support for searching pdf text?

### ISSUE THREAD

**Issue by gideondsouza** [jung-kurt/gofpdf#113]
Essentially I'm looking to build a web viewer with this library and was wondering if it has a search function which will give me the point co-ordinates of a piece of text.

If it isn't there I'd be very happy to work on it and send a PR :)

**Comment by jung-kurt** [comment]
When generating a PDF, [`GetXY()`](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.GetXY) gives you the current position where text will be placed. But, no, gofpdf doesn't provide any means of finding _where_ text has already been placed. If you intend to parse an already completed PDF, there are likely better libraries out there. ([PDFtk](https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/) comes to mind.)

**Comment by gideondsouza** [comment]
Actually I was looking for a go library since this will be a go web app. 

Doesn't this library have a method to read search a piece of pdf text.  Then I could add a method to get it's co-ordinates.

**Comment by jung-kurt** [comment]
> Doesn't this library have a method to read search a piece of pdf text.

No. This library only writes PDFs (the easy part), it does not parse them.

**Comment by gideondsouza** [comment]
:) I see. Alright. Thanks for your reply.
