### ISSUE TITLE
En dash is being turned into â “ / ñ is turned into Ã±o?

### ISSUE THREAD

**Issue by CWright777** [jung-kurt/gofpdf#114]
The pdfs that are being generated have certain characters that do not get reproduced correctly. ñ and en dash are just a couple of them. Is there a work around or fix for this?

Thanks!

**Comment by jung-kurt** [comment]
This seems to be an code page issue. Have you followed the steps taken in the [codepage example](https://github.com/jung-kurt/gofpdf/blob/14c1db30737a138f8d9797cffea58783892b2fae/fpdf_test.go#L1234-L1261)?

**Comment by CWright777** [comment]
I have not. I will give that a shot. Thanks jung-kurt.
