### ISSUE TITLE
Crash without error reporting if no font is specified

### ISSUE THREAD

**Issue by alialamine** [jung-kurt/gofpdf#116]
How to reproduce: Create a new document, and a page inside of it. Then CellFormat(...) before setting the font. 

This command and any other command following it will fail to execute, without any warning or error returned.

**Comment by jung-kurt** [comment]
Thanks, @alialamine -- I'll investigate.

**Comment by jung-kurt** [comment]
An error is now explicitly returned when attempting to render text without first having set the font.

Thanks for reporting this, @alialamine.

**Comment by alialamine** [comment]
Ty. And nice work on the library. I think we can close this now.
