### ISSUE TITLE
Indicate Last Page on Footer Func

### ISSUE THREAD

**Issue by aloidev** [jung-kurt/gofpdf#121]
Hi,
I need gofpdf to indicate Last Page my use case is 
 - Print Subtotal on every page exept the last page. 
 - Print Some Notes only on Last Page.
I can not found the on gofpdf how to indicate Last Page especially on Footer Func,
I've able to get it by doing small change to the gofpdf by change Footer Func signature to func(bool) and set it true when endpage call Footer Func.
If you like to add this to gofpdf i need your suggestion  which one you preferred : 
 - Change Footer Func signature (this maybe break other perople code) 
 - Add New Method for to set new footer func signature.

**Comment by jung-kurt** [comment]
Thanks for calling my attention to this issue -- it's definitely a real use case but I haven't had a need for it yet.

My preference is to add a new method in order to preserve backwards compatibility.

Thanks!

**Comment by jung-kurt** [comment]
Merged. Thanks, @aloidev
