### ISSUE TITLE
Copyright Symbol Encoding Issue

### ISSUE THREAD

**Issue by hiendv** [jung-kurt/gofpdf#123]
`Copyright \u00a9 2017` and `Copyright © 2017` are rendered as `Copyright Â© 2017`

My sample code
```golang
pdf.SetY(-40)
pdf.Ln(15)
pdf.SetFont("Arial", "", 10)
pdf.CellFormat(0, 20, "Copyright © 2017 Company.", "0", 0, "C", false, 0, "")
pdf.Ln(5)
pdf.CellFormat(0, 20, fmt.Sprintf("Page %d/{nb}", pdf.PageNo()), "0", 0, "C", false, 0, "")
```

**Comment by jung-kurt** [comment]
Try the following:

```
tr := pdf.UnicodeTranslatorFromDescriptor("") // "" defaults to "cp1252"
pdf.CellFormat(0, 20, tr("Copyright © 2017 Company."), "0", 0, "C", false, 0, "")
```

See [`ExampleFpdf_CellFormat_codepage()`](https://github.com/jung-kurt/gofpdf/blob/e79bdb537c4e4e719b91d5f35afa9f54976e0d4d/fpdf_test.go#L1349-L1389) for an example on how to use [`UnicodeTranslatorFromDescriptor()`](http://godoc.org/github.com/jung-kurt/gofpdf#UnicodeTranslator).

**Comment by hiendv** [comment]
Thank you. It works flawlessly.
