### ISSUE TITLE
Disable autolinking

### ISSUE THREAD

**Issue by hiendv** [jung-kurt/gofpdf#124]
I need to disable the autolinking in the pdf.
```go
pdf.CellFormat(5, 6, "www.domain.com", "LR", 0, "", fill, 0, "") // Result in a hyper link
pdf.CellFormat(5, 6, "domain.com", "LR", 0, "", fill, 0, "") // Result in plain text
```

**Comment by jung-kurt** [comment]
Good catch. This is really curious behavior. From an [Adobe forum](https://forums.adobe.com/thread/2023638):

> When Acrobat Reader encounters URL text, such as "http://www.adobe.com" and "somebody@adobe.com", it automatically converts the URL text to links on the fly.

> The feature can be enabled/disabled by selecting/deselecting the General > "Create links from URLs" option in the Preferences dialog.

Evidently, some PDF readers can be configured to not autolink text that look like URLs. I am not sure if this can be switched on and off within the PDF document itself. Do any other readers of this thread know if this is possible?

**Comment by hiendv** [comment]
I can confirm Chrome reader does auto-link but Ubuntu Document Viewer does not. This should not be gofpdf's problem.
