### ISSUE TITLE
UnicodeTranslatorFromDescriptor can return nil

### ISSUE THREAD

**Issue by flibustenet** [jung-kurt/gofpdf#128]
Hi,

In the doc of `UnicodeTranslatorFromDescriptor` it says: 

>  // If an error occurs reading the descriptor, the returned function is valid
>  // but does not perform any rune translation.

But if the pdf is in error it return nil `if f.err != nil { return } ` which panic if we use this nil function of course.

Is it a mistake ?

**Comment by jung-kurt** [comment]
Good catch, @flibustenet. Corrected in ef5029596657de75a312ed095fd29ec7aacee058

**Comment by flibustenet** [comment]
I had a bug report at 17:20, 20 minutes after i could see from where it come thanks to clearness of Go and 2 hours after you corrected it on the other side of the ocean for all the community. It's amazing.
Thanks

**Comment by jung-kurt** [comment]
Your identification of the problematic code made the solution easy!

Wonderful pictures of bicycling through France. Delightful.
