### ISSUE TITLE
Question: Page background design

### ISSUE THREAD

**Issue by vegh1010** [jung-kurt/gofpdf#130]
Is it possible to set page's background design and apply to all pages? such as adding rectangle with blue filling at the top and bottom page.

**Comment by jung-kurt** [comment]
Yes, this can be done easily. One way is to add the page styling code to the header function. For example, in the [`AddPage()`](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.AddPage) example, modify the function passed to [`SetHeaderFunc()`](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.SetHeaderFunc) as follows:

```go
pdf.SetHeaderFunc(func() {
    pdf.Image(example.ImageFile("logo.png"), 10, 6, 30, 0, false, "", 0, "")
    pdf.SetY(5)
    pdf.SetFont("Arial", "B", 15)
    pdf.Cell(80, 0, "")
    pdf.CellFormat(30, 10, "Title", "1", 0, "C", false, 0, "")
    pdf.Ln(20)
    // --- background ---
    x, y := pdf.GetXY()
    r, g, b := pdf.GetFillColor()
    pdf.SetFillColor(200, 200, 248)
    pdf.Rect(40, 40, 130, 217, "F")
    pdf.SetFillColor(r, g, b)
    pdf.SetXY(x, y)
    // --- end of background
})
```

**Comment by vegh1010** [comment]
alright thanks
