### ISSUE TITLE
Write on image

### ISSUE THREAD

**Issue by hrvylein** [jung-kurt/gofpdf#134]
Is it possible to write on an image? I added a full screen image (A4) to my page wih ImageOptions but when trying to write on it, a page break occurs. Any hint?

**Comment by jung-kurt** [comment]
The documentation for [`ImageOptions()`](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.ImageOptions) says

> If flow is true, the current y value is advanced after placing the image and a page break may be made if 
necessary.

I think what you want to do is set flow to false, and then use [`SetXY()`](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.SetXY) to reposition the current position to write text on top of your image.

**Comment by hrvylein** [comment]
Thanks! That's what I was looking for.
