### ISSUE TITLE
How to save PDF file to a directory ?

### ISSUE THREAD

**Issue by calba5141114** [jung-kurt/gofpdf#135]
I know this is a noob question but how do save the file to a directory?

**Comment by jung-kurt** [comment]
Like this?

err = pdf.[OutputFileAndClose](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.OutputFileAndClose)("/path/to/some.pdf")

**Comment by calba5141114** [comment]
It's not working

**Comment by jung-kurt** [comment]
The following works for me.

```go
package main

import (
        "fmt"
        "github.com/jung-kurt/gofpdf"
        "os"
)
func main() {
        pdf := gofpdf.New("P", "mm", "A4", "")
        pdf.AddPage()
        pdf.SetFont("Arial", "B", 16)
        pdf.Cell(40, 10, "Hello world")
        err := pdf.OutputFileAndClose("/tmp/hello.pdf")
        if err != nil {
                fmt.Fprintf(os.Stderr, "error writing to /tmp/hello.pdf")
        }
}
```
The directory must already exist. (See [`os.MkdirAll()`](https://golang.org/pkg/os/#MkdirAll) if this is not the case.)

Please include the smallest example of a program that does not work for you.

**Comment by calba5141114** [comment]
package main

import "github.com/jung-kurt/gofpdf"




func main (){
pdf:=gofpdf.New("P","mm","A4", "")
pdf.AddPage()
pdf.SetFont("Arial","B",16)
pdf.Cell(40,10,"Hello, World")
err := pdf.OutputFileAndClose("C:\Users\GRAND_MASTER_FLEX\Desktop\hello.pdf")


}

**Comment by calba5141114** [comment]
thank you

**Comment by jung-kurt** [comment]
Ah, Windows. You may want to use [`filepath.FromSlash()`](https://golang.org/pkg/path/filepath/#FromSlash) in order to avoid problems with backslashes. For example,
```go
pdf.OutputFileAndClose(filepath.FromSlash("C:/Users/GRAND_MASTER_FLEX/Desktop/hello.pdf"))
```
