### ISSUE TITLE
Question: Background of pages?

### ISSUE THREAD

**Issue by j8** [jung-kurt/gofpdf#141]
How can add different background color to each page?

**Comment by jung-kurt** [comment]
See issue #130. The idea is to draw a filled rectangle and restore the cursor to the place you want it. If you are using automatic page breaks, then you will want to register a function with [SetAcceptPageBreakFunc()](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.SetAcceptPageBreakFunc) and handle the color filling in it.
