### ISSUE TITLE
Question: Support for spot colors?

### ISSUE THREAD

**Issue by alexsasharegan** [jung-kurt/gofpdf#142]
Does this library have support for spot colors? I've searched the documentation, and I didn't see any explicit mention of them.

**Comment by jung-kurt** [comment]
> Does this library have support for spot colors?

gofpdf currently does not support spot colors. However, it looks relatively straightforward to do so. Would a port of [this script](http://www.fpdf.org/en/script/script89.php) work for your purposes?

**Comment by alexsasharegan** [comment]
That does look sufficient. I'm trying to get out of PHP land using TCPDF in favor of scripting print file generation with go.

I need to draw images and then make CNC cutting paths using a spot color so the print rip software can pickup the special cut paths and generate workflow files for printer and cutter. I don't even need a specific Pantone, just has to be a spot color.

**Comment by alexsasharegan** [comment]
The corresponding section currently being used in the TCPDF script can be found here: https://github.com/tecnickcom/TCPDF/blob/master/tcpdf.php#L3732

**Comment by jung-kurt** [comment]
> I need to draw images and then make CNC cutting paths using a spot color so the print rip software can pickup the special cut paths and generate workflow files for printer and cutter. 

Cool project! Thanks for the tcpdf link. I'll try to get to this in the next few days. The only snag I see is some friction with the regular RGB color routines. For example, I am not sure what a routine like `GetDrawColor()` should return when the current color is a CMYK value. Possibly a more general replacement like `GetDrawColorGeneral()` that can return either form. However, it seems likely that if a PDF uses spot colors, it will use them exclusively, so maybe spot-specific methods like `GetDrawSpotColor()` will suffice as long as the documentation warns about the two different systems. Any comments?

**Comment by alexsasharegan** [comment]
I'll hazard a few comments, but I'm not familiar enough with your api to have any definite opinions.

It might be beneficial to refactor the `GetDrawColor` into more of an adapter function. Perhaps calling it with an exported package enum `fpdf.ColorRGB | fpdf.ColorCMYK` where those are just type aliased ints. Then you could have `GetDrawColorRGB` & `GetDrawColorCMYK`. The generic function could just switch off the enum to call the correct method.

Since there aren't any default params in go, this would be a breaking change—so probably not the best case. Maybe this could be implemented in the general method you mentioned: `GetDrawColorGeneral()`. I'm still a go newcomer, but I feel like it is more idiomatic to take the explicit approach and use `GetDrawSpotColor()`, `GetDrawRGBColor()`, `GetDrawCMYKColor()`, etc. Perhaps a future major version could move to explicit color methods only.

I don't think that usage of a spot color would likely indicate a pdf made up exclusively of spot colors. In print, usage of a spot color means paying a bit extra, so it's usually kept to a minimum (e.g. paying for a pre-mixed spot color that is your brand critical color). Spots are also used for white ink and special varnish application. These typically get applied as special touches on an otherwise cmyk file.

**Comment by marcusatbang** [comment]
Colours in PDFs are really quite complicated (see eg [transparency blend modes when a document contains RGB and CMYK objects](https://forums.adobe.com/message/3142774#3142774) and the fact that non-adobe readers don't always respect that setting, which bit me a few years ago). There are also more then just the three colour types you list.

I like the option of `GetDrawSpotColor()`, `GetDrawRGBColor()` and `GetDrawCMYKColor()`, with the caveat that there could be other stranger ones. The basic `GetDrawColor()` could be left, or could be repurposed to return an interface (which would be a breaking change).

**Comment by jung-kurt** [comment]
> Colours in PDFs are really quite complicated

You're right -- I hadn't considered gradients and other color routines other than simple fill/draw/text output. To do this right, the whole color system would have to be factored. Also, for my own purposes, rather than have a `GetFillColor()` routine, I would prefer an internally managed color stack. For example, `PushSpotFillColor()` and `PopFillColor()`, where the pop method reinstates the most recently used fill color, regardless of its type.

With 7751c17f106d9d7d4c6c290b969ece1c8dab4371 I have added simple support and added caveats to the documentation of `GetFillColor()` and friends.
