### ISSUE TITLE
Help needed: Word wrap without expanding cell height / CellFormat with multiline text

### ISSUE THREAD

**Issue by igorsousa-b** [jung-kurt/gofpdf#143]
Is there any way to print some multi-line text in a cell without expanding the cell's height? Whenever I search for word-wrap or something related, I get pointed towards multicell. This does not work for me, as I wish to use the cell to stay same. If the multi-line text doesn't fit vertically, it shouldn't show up. When it does need to show up, the cell's height is already set to accommodate it.

I could try to achieve this manually but if there is some built-in way to do it, it would be much preferred.

Another related issue: to create a multiline string, I use SplitLines on the string and then strings.Join the array (after converting from [][]byte to []string) with a \n between each item. When log.Printing, the string is formatted correctly but when I use CellFormat to place it in the PDF, it still shows up as single-line.
Does CellFormat ignore line-breaks in the text param? If so, how do I get around it without using MultiCell due to the other issues mention above?

**Comment by jung-kurt** [comment]
You'll have to accomplish this manually using [SplitLines()](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.SplitLines) and [MultiCell()](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.MultiCell). ([CellFormat()](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.CellFormat) is for single lines of text only -- as you found, it does not honor newline characters.) 

If the number of lines returned by `SplitLines()` is greater than can fit in your cell, skip. If it is the same as can fit, join as you did with `strings.Join()` and use `MultiCell()` to display. If it is fewer, you can augment the list returned by `SplitLines()` with some empty lines and then proceed with the preceding step.

**Comment by igorsousa-b** [comment]
@jung-kurt Thank you, the solution makes sense and I'm implementing it right now.

An issue came up with SplitLines(), however. If it detects that a word is going to put a line over the allowed width, it cuts that entire word, correct? Can the "cutting" be done by character/letter instead of the entire word?

**Comment by jung-kurt** [comment]
> An issue came up with SplitLines(), however. If it detects that a word is going to put a line over the allowed width, it cuts that entire word, correct? 

Yes, it breaks on ' ', '\t', and '\n'. 

> Can the "cutting" be done by character/letter instead of the entire word?

Not as it stands. Your best bet my be to copy [the source](https://github.com/jung-kurt/gofpdf/blob/7751c17f106d9d7d4c6c290b969ece1c8dab4371/fpdf.go#L2010-L2059) method and adjust the break logic accordingly.

**Comment by igorsousa-b** [comment]
Alright, will do that. Cheers for the help.

**Comment by jung-kurt** [comment]
Good luck! If your solution is general, consider a pull request.

**Comment by igorsousa-b** [comment]
It is done but I'm not sure if it's worth a pull request. All I did was take Bruno Michel's SplitLines() method and replace
`if c == ' ' || c == '\t' || c == '\n' {
`sep = i`
}`
with 
`sep = i`

This will split by character instead of space.

**Comment by jung-kurt** [comment]
Thanks for the update, @igorsousa-b. Elegant change to meet your use case.

**Comment by pruse2402** [comment]
> You'll have to accomplish this manually using [SplitLines()](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.SplitLines) and [MultiCell()](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.MultiCell). ([CellFormat()](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.CellFormat) is for single lines of text only -- as you found, it does not honor newline characters.)
> 
> If the number of lines returned by `SplitLines()` is greater than can fit in your cell, skip. If it is the same as can fit, join as you did with `strings.Join()` and use `MultiCell()` to display. If it is fewer, you can augment the list returned by `SplitLines()` with some empty lines and then proceed with the preceding step.

can I get the example program?
