### ISSUE TITLE
insert another pdf's as xobjects ?

### ISSUE THREAD

**Issue by Gys** [jung-kurt/gofpdf#148]
Hi there

How difficult would it be to add support to insert another pdf as a kind of image ? Kind of embedding several smaller pdf's into the page of another one ? From the little that I found on this subject it seems 'xobject' is a way to implement that. But it also means the pdf's to be embedded have to be pre-processed ?

I am not very familar with the pdf format and workings. But we currently use some ancient tool to create pages in one pdf where each page contains a lot of smaller pdf's. At some point we will need to replace this tool.

**Comment by jung-kurt** [comment]
Templates, which use `xobject` and are embedded into a page, are supported, but there is no support for embedding a standalone PDF that has already been generated. That would involve parsing and merging the components of the child PDF, something that is pretty far afield from the current objective of the library.

**Comment by jung-kurt** [comment]
Please reopen if needed.
