### ISSUE TITLE
Connect tutorials better with methods

### ISSUE THREAD

**Issue by stanim** [jung-kurt/gofpdf#15]
As the number of tutorials are growing, it gets hard to quickly look up some example code. Now you first have to find a relevant function, read the tutorial number and scroll back. It would maybe more efficient to have some keywords in the title instead of just a number. 

So instead of:
- ExampleFpdf_tutorial31

it could be:
- ExampleFpdf_tutorial31_line_caps_join_style (does not give golint error)
- ExampleFpdf_tutorial31LineCapsJoinStyle
- ExampleFpdf_31_line_caps_join_style (does not give golint error)
- ExampleFpdf_31LineCapsJoinStyle

**Comment by jung-kurt** [comment]
Good point. That would be a definite improvement. 

Another approach would be to link the example with the principal method demonstrated. (Unfortunately, there can be only one I think.) Then the link would show up in the documentation where it would most likely be followed.

**Comment by stanim** [comment]
Both approaches would be a big improvement of the current situation. (godoc builds automatically a list of all examples anyway at the beginning of the documentation.) Your suggested approach is probably more idiomatic. For each tutorial the main method should be chosen (if there is more than one, I would chose the alphabetical first). The other demonstrated methods need to keep the reference to the example.

So for tutorial 31: `SetLineCapsStyle` and `SetLineJoinStyle` are equally important. So the example would land at `SetLineCapsStyle` and `SetLineJoinStyle` would mention "see the example of SetLineCapsStyle"  instead of "see tutorial 31".

**Comment by jung-kurt** [comment]
Perfect.

I'll take this on. However, if you are so inclined, feel free to begin with your tutorials.

**Comment by stanim** [comment]
Sure, I'll do my own.

**Comment by jung-kurt** [comment]
It looks like `OutputAndClose` will need a little work to accommodate the new scheme, so unless you have already plunged in, it may be best to wait a bit until I get that ironed out. The purpose of that routine is to minimize boilerplate for the examples, but maybe getting rid of it would actually help programmers copy-and-paste the examples.

**Comment by jung-kurt** [comment]
Sorry -- `docWriter` is the routine I meant, not `OutputAndClose`.

**Comment by stanim** [comment]
I'll wait for your green light.

**Comment by jung-kurt** [comment]
I think the most [recent commit](https://github.com/jung-kurt/gofpdf/commit/fc105cd6b119a1f2f14cc411aeb881dca26fab23) uses a satisfactory pattern. I pay a little more attention to the comment above the example call, and replace 
```
pdf.OutputAndClose(docWriter(pdf, 5))
```
with something like
```
fileStr := exampleFilename("multicolumn")
err := pdf.OutputFileAndClose(fileStr)
summary(err, fileStr)
```
These three lines could easily be factored into a single call, but I think it's best to expose the call to `OutputFileAndClose` for the purposes of an example.

**Comment by stanim** [comment]
I agree to expose OutputFileAndClose. It was not clear how to save a file when I was reading the examples for the first time.

**Comment by stanim** [comment]
When you are done with all other tutorials, give me a sign and I'll do mine.

**Comment by jung-kurt** [comment]
While I was in sewing machine mode I went ahead and did yours. Feel free to revise my changes.

**Comment by marcusatbang** [comment]
> sewing machine mode

:)

**Comment by stanim** [comment]
Looks perfect! I was wondering if it wouldn't be handy to add the link to the example, if it is located somewhere else. This makes it much more easy to jump around. (See https://godoc.org/github.com/fluhus/godoc-tricks#Links). It is a bit more work, but increases the usability of the documentation.

For example:
```go
// LineTo creates a line from the current stylus location to (x, y), which
// becomes the new stylus location. Note that this only creates the line in
// the path; it does not actually draw the line on the page.
//
// The MoveTo() example demonstrates this method.
// (http://godoc.org/github.com/jung-kurt/gofpdf#example-Fpdf-MoveTo)
func (f *Fpdf) LineTo(x, y float64) {
	f.outf("%.2f %.2f l", x*f.k, (f.h-y)*f.k)
	f.x, f.y = x, y
}
```
Will be converted in:

> LineTo creates a line from the current stylus location to (x, y), which becomes the new stylus location. Note that this only creates the line in the path; it does not actually draw the line on the page.
> 
> The MoveTo() example demonstrates this method. ([http://godoc.org/github.com/jung-kurt/gofpdf#example-Fpdf-MoveTo] (http://godoc.org/github.com/jung-kurt/gofpdf#example-Fpdf-MoveTo))

**Comment by jung-kurt** [comment]
Links would be very useful. However, I have reservations about adding URLs that bind the documentation to a host so tightly. This could lead to version mismatches when the documentation is read from a different server (I typically use godoc in http-mode) or in the context of a repository fork. 

One needs to lament that the Go team didn't see fit to support self-relative links.

I'll continue to mull this one over.

**Comment by stanim** [comment]
Fair enough.
