### ISSUE TITLE
ImageOptions tries to open image registered using RegisteredImageOptionsReader

### ISSUE THREAD

**Issue by uorji3** [jung-kurt/gofpdf#152]
I am creating a pdf that uses a `headerLogo` image that is defined in my code as a base64 encoded string. I am receiving the following error from the `fpdf.ImageOptions` function:  `open headerLogo: no such file or directory.`

Here is a snippet of my code:
```
fpdf.RegisterImageOptionsReader("headerLogo", options, bytes.NewReader(b))
fpdf.SetXY(43, 15)
fpdf.ImageOptions("headerLogo", 43, 15, 90, 20, true, options, -1, "")
```
I convert my base64 encoding string to a `Reader` and use `fpdf.RegisterImageOptionsReader.`
I then use ImageOptions to place the image at the preset location.

I've studied the code and it looks like the issue is the following
- ImageOptions calls RegisterImageOptions [here](https://github.com/jung-kurt/gofpdf/blob/master/fpdf.go#L2484).
- RegisterImageOptions then tries to open the file if the image hasn't been registered yet [here](https://github.com/jung-kurt/gofpdf/blob/master/fpdf.go#L2591).

Questions
1. Has anyone had an issue in which the `RegisterImageOptionsReader` failed to properly register image?
2. Can we modify `ImageOptions` or add another function that will draw the image if it has been properly registered but will not try to open a file if it has not?

**Comment by jung-kurt** [comment]
My question is why [f.images[imgName] = info](https://github.com/jung-kurt/gofpdf/blob/1bef4f81c40b64d68788e590003f4f8fbdc4d296/fpdf.go#L2560) does not seem to have been executed in `RegisterImageOptionsReader()`. That would keep the file logic from ever being reached. Might there be an error condition that causes a short return in `RegisterImageOptionsReader()`? You can check with `Error()`.

**Comment by uorji3** [comment]
This code was being used by my web server and it would cause intermittent failure.
I changed up my code a bit and I included a check to see if the image has been registered with `GetImageInfo()` so I don't expect any more fatal failures going forward.

Not exactly sure what caused the failure before but I will close this issue since it appears no else has had this problem.
