### ISSUE TITLE
Is there an easy way to parse PDF hyperlinks?

### ISSUE THREAD

**Issue by pieterclaerhout** [jung-kurt/gofpdf#153]
I'm wondering if there's an sample which shows how to parse PDF hyperlinks to urls and other pages.

There is the annotation example, but that only lists the annotations, I cannot find a way to make any sense out of this.

**Comment by jung-kurt** [comment]
A number of functions let you write internal links or URLs (for example `CellFormat()`, `Image()`, `Link()`, `LinkString()`, etc) when you create a document. However, since this library only generates PDFs and cannot read them, there is no parsing of PDFs to extract links.
