### ISSUE TITLE
Tab handling

### ISSUE THREAD

**Issue by mandolyte** [jung-kurt/gofpdf#154]
I noticed today that the Write() function seems to ignore tab characters. Not hard to work around, but wondered if this is expected behavior or a bug?

I do not see anything in the docs about a tab handling...

Thanks for such an easy package to use!
Cecil

**Comment by jung-kurt** [comment]
Here is a remark about tabs and PDFs from a [Stackflow answer](https://stackoverflow.com/questions/27743936/how-to-substitude-all-t-tab-characters-with-white-space-in-a-pdf) on that topic:

> The 'tab' character (0x04 in ASCII) has no special significance in PDF, and in particular it does not move the current point, it simply draws a glyph. As a result, if you do (A\tB) what you will see when the PDF is rendered is 'AB'. Or 'A*B' where the * is some other character you didn't expect (often a square)

gofpdf doesn't do anything special with tabs, but it lets you control text placement, so one possibility is to code up a tab writer, perhaps something like the [HTMLBasicType](https://godoc.org/github.com/jung-kurt/gofpdf#HTMLBasicType). If you make it general enough, consider sharing it with a pull request!

> Thanks for such an easy package to use!

Thanks -- glad you find it useful.

**Comment by mandolyte** [comment]
Thanks! Closing this issue.
