### ISSUE TITLE
Q. Interaction between line height and font (size)

### ISSUE THREAD

**Issue by mandolyte** [jung-kurt/gofpdf#155]
I am seeing some unexpected spacing in a document I am creating (markdown to PDF effort). I think it may be that I don't understand how a line of text is fitted within the line height. I did not see anything in the documentation on how LH and font size interact. In my sample output [here](https://github.com/mandolyte/examples-gofpdf/blob/master/mdToPdf/test.pdf) you can see that the line of text following each heading has more space as the heading font size gets smaller. In millimeters, the paragraph after heading 1 is 4mm below the heading (letter H), whereas after heading 6, the space is 7.5mm. I am changing a number of factors for each heading level, but I can't explain the varying gap. 

Thanks for any pointers/advice!

**Comment by jung-kurt** [comment]
gofpdf treats font size and line height independently. Font size determines the vertical space that rendered glyphs consume, and line height tells the library how big a text box should be. The caller has control over line height so that it can manage different font sizes on a given line. It looks like you will want to set the line height to match the font used in block elements like h1, h2, etc. The second value returned from [GetFontSize()](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.GetFontSize) can be of use here.

Your project looks interesting! I look forward to using it in the future.

**Comment by mandolyte** [comment]
Suppose I have a 20pt line height and a 10pt font size. How will the text be vertically aligned within the 20pt line height? For example, will the font be fit to the bottom and the excess at the top? Or is the excess distributed equally above and below the text?

Thanks for the help!

**Comment by jung-kurt** [comment]
The documentation for [CellFormat()](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.CellFormat) includes the following:

> Vertical alignment is controlled by including "T", "M", "B" or "A" (top, middle, bottom, baseline) in alignStr. The default alignment is left middle.

So, without delving into the code too deeply, it looks like the excess space is distributed equally by default. The baseline option is likely the most useful.

**Comment by mandolyte** [comment]
So far, with the sole exception of "code blocks", I have avoided use of CellFormat(), relying only on Write(). Is there a way to control vertical alignment using Write()? Or perhaps I'm not taking advantage of CellFormat() as much as I should (it seemed restrictive to me to treat the text as if was in a "table")?

**Comment by jung-kurt** [comment]
[Write()](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.Write) is definitely convenient. Probably it makes sense to factor [write()](https://github.com/jung-kurt/gofpdf/blob/c8debdafb5eeac8330420d4b1699cc1094237805/fpdf.go#L2198-L2270) (which is called by Write() and in turns calls CellFormat()) to include an option struct. Currently, write() calls CellFormat() with no alignment, so by default the text is placed horizontally on the left and vertically in the middle.

**Comment by mandolyte** [comment]
After some debugging I found the problem. I was issuing the newline after the heading after changing back to "normal" font. After swapping to write the newline with the heading-sized line height in effect first, problem solved. Lessons learned...

**Comment by jung-kurt** [comment]
Good catch!
