### ISSUE TITLE
Strike through example

### ISSUE THREAD

**Issue by mandolyte** [jung-kurt/gofpdf#157]
I was looking for precedence on how to handle ~strike though font style~ but didn't find any. Nor did I find any requests for it. Any pointers?

If not consider this an enhancement request :-)

**Comment by jung-kurt** [comment]
From a quick search, it looks like the only way to do this is to draw a line over the text between the appropriate coordinates. Unfortunately, [GetStringWidth()](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.GetStringWidth) can return spurious results if the space between words has been adjusted to account for text justification. It seems like the right approach would be to note the starting position of the cursor before writing text in [CellFormat()](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.CellFormat) and draw a line to it after writing the text. This could be complicated by the `ln` argument that specifies what happens to the cursor after drawing text.

**Comment by tcd** [comment]
@mandolyte 

```go
// Write text then draw a line through it.
func strike(pdf *gofpdf.Fpdf, txt, styleStr string) {
	pdf.SetFont("helvetica", styleStr, 12)
	pdf.SetLineWidth(0.25)
	width := pdf.GetStringWidth(txt)
	_, lineHt := pdf.GetFontSize()

	// Where the text starts, also where to start the strikethrough line.
	x := pdf.GetX()
	y := (pdf.GetY() + (lineHt / 2))

        // Write out your text
	pdf.Write(lineHt, txt)

        // Then strike through
	pdf.Line(x, y, x+width, y)
}
```

**Comment by mandolyte** [comment]
Thanks!
