### ISSUE TITLE
Html to pdf Not Reder Css style sheet 

### ISSUE THREAD

**Issue by MuthukumarHelios** [jung-kurt/gofpdf#159]
[See line](https://github.com/jung-kurt/gofpdf/blob/master/fpdf_test.go#L627)
**I am using the above function with some modificaiton**

```go
func ExampleFpdf_HTMLBasicNew() {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetFont("", "U", 0)
	link := pdf.AddLink()
	pdf.AddPage()
	pdf.SetLink(link, 0, -1)
	pdf.Image(ImageFile("http://api.qrserver.com/v1/create-qr-code/?data=HelloWorld"), 10, 12, 30, 0, false, "http://api.qrserver.com/v1/create-qr-code")
	
	pdf.SetFont("Helvetica", "", 20)
	_, lineHt := pdf.GetFontSize()
	// _, lineHt = pdf.GetFontSize()
	htmlStr := `<html><body><h1 style="color:red;">This is an html from pdf to test color<h1><img src="http://api.qrserver.com/v1/create-qr-code/?data=HelloWorld" alt="img" height="42" width="42"></img></body></html>`
	html := pdf.HTMLBasicNew()
	// html.Write(lineHt, htmlStr)
	html.Write(lineHt,htmlStr)
	fileStr := Filename("Fpdf_HTMLBasicNew")
	err := pdf.OutputFileAndClose(fileStr)
	Summary(err, fileStr)
}
```
>The Pdf is generating with The proper Extension and Proper Text 

**Error**

### My Css styles  and  Image Tags are not Applying to the Generated pdf
I don't Know What i am doing Wrong 

Is there is any Other Function in  our Plugin which converts Html to Pdf 
Any help Will be Appreciated

**Comment by jung-kurt** [comment]
Hi @MuthukumarHelios,

[HTML in gofpdf](https://godoc.org/github.com/jung-kurt/gofpdf#HTMLBasicType) is *very* limited. It does not support CSS or images. 

You will have better luck using low-level methods. For example,

```go
package main

import (
	"fmt"
	"github.com/jung-kurt/gofpdf"
	"os"
)

func main() {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.AddPage()
	pdf.SetFont("Arial", "", 14)
	pdf.Image("helloworld.png", 10, 10, 30, 0, false, "", 0, "")
	pdf.SetTextColor(232, 81, 64)
	pdf.Text(10, 50, "Here is some red text")
	err := pdf.OutputFileAndClose("hello.pdf")
	if err != nil {
		fmt.Fprintf(os.Stderr, "%s\n", err)
	}
}
```

**Comment by MuthukumarHelios** [comment]
Thank You @jung-kurt 
I my Case i have to Compile my Dynamic html and Covert it into Pdf 
In our Plug-in I thing It's Not Possible {I might Be Wrong}

**Comment by jung-kurt** [comment]
You may want to investigate [headless Chrome](https://developers.google.com/web/updates/2017/04/headless-chrome).
