### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by stanim** [jung-kurt/gofpdf#16]
I want to use [Sourcegraph](https://sourcegraph.com) for gofpdf code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/jung-kurt/gofpdf. (It should only take 30 seconds.)

Thank you!

**Comment by jung-kurt** [comment]
Looks interesting. I'm new to this and don't quite understand why Sourcegraph would need write (in addition to read) access for webhooks, services and commit statuses.

**Comment by stanim** [comment]
Only do it, if you feel comfortable with it. This person of Sourcegraph can answer your question: https://github.com/sqs.

**Comment by jung-kurt** [comment]
Thanks -- I'll inquire.

**Comment by jung-kurt** [comment]
It looks like Sourcegraph is modifying its policies in the next few days. I'll wait for the changes to proceed with this.

**Comment by jung-kurt** [comment]
Still waiting on the promised permission policy changes at Sourcegraph.

**Comment by jung-kurt** [comment]
I've tried unsuccessfully to enable this several times in the last few months. If anyone knows how to get past the 403 (Forbidden) error at Sourcegraph, let me know and I'll try again. Until then, I will close this issue.
