### ISSUE TITLE
Help: Create Nested List

### ISSUE THREAD

**Issue by vegh1010** [jung-kurt/gofpdf#161]
Hi,

Is there any example to create nested list where you can either use numbering or bullet points?

**Comment by jung-kurt** [comment]
Sean Benoit wrote a script for FPDF that makes either ordered or ordered lists. It doesn't look like it would be too much trouble to adapt it to gofpdf. It appears to support nested lists by means of the Indent record value, although it doesn't look like the automatic numbering accounts for changes in indentation.

See [http://www.fpdf.org/en/script/script56.php]()

**Comment by ajstarks** [comment]
pdfdeck (which uses gofpdf) supports lists 

see: 
https://github.com/ajstarks/deck 
https://github.com/ajstarks/deck/tree/master/cmd/pdfdeck
https://github.com/ajstarks/deck/blob/master/examples/deck.pdf

**Comment by jung-kurt** [comment]
Please reopen issue if the links provided by @ajstarks don't meet your needs.

**Comment by KevinStirling** [comment]
Hi, I just stumbled upon this thread while looking for a way to do something similar to this. Is there a way add bullet points in a cell on an individual basis? Like inserting a single unicode character? Sorry to use this as a support thread but I'm really struggling to find a way to do this

**Comment by jung-kurt** [comment]
Unfortunately, gofpdf is really limited when it comes to unicode. It only handles fonts that are stored in code pages, that is, sets of up to 256 characters. What may help you is the [Zapf Dingbats codepage](https://en.wikipedia.org/wiki/Zapf_Dingbats) that is included in all PDF readers. Here is an example:
```go
package main

import (
	"fmt"
	"github.com/jung-kurt/gofpdf"
	"os"
)

func main() {
	const fontHt = 18
	pdf := gofpdf.New("P", "mm", "A4", "")
	lineHt := pdf.PointToUnitConvert(fontHt)
	pdf.AddPage()
	for j := 1; j < 12; j++ {
		pdf.SetFont("zapfdingbats", "", fontHt/4)
		pdf.CellFormat(5, lineHt, "\x6c", "", 0, "R", false, 0, "")
		pdf.SetFont("times", "", 18)
		pdf.CellFormat(5, lineHt, fmt.Sprintf(" Item %d", j), "", 1, "L", false, 0, "")
	}
	err := pdf.OutputFileAndClose("bullet.pdf")
	if err != nil {
		fmt.Fprintf(os.Stderr, "error writing to bullet.pdf: %s\n", err)
	}
}
```

**Comment by KevinStirling** [comment]
nice! thank you very much for the example!
