### ISSUE TITLE
[question]: what spec info do you use to develop a pdf lib?

### ISSUE THREAD

**Issue by alexsasharegan** [jung-kurt/gofpdf#164]
This is just a question for my edification, so I'm going to immediately close this so it doesn't clog your open issues.

When you started developing this lib, what documents/specs did you consult to know how to write the raw pdf data? I source-dive a couple pdf libs in different languages and I start to see how pdf's work, but where did you learn it?

I want to start hacking on some low level pdf stuff since I work at a graphics print company, but I don't know where to start. Can you give me some resource links or pointers? You've been really helpful and responsive on issues in the past, so I thought to reach out to you.

Thanks for all your open source work!

**Comment by mpingram** [comment]
Disclaimer: I'm a new contributor, and not a pdf expert. I made heavy use of Adobe's version of the PDF 1.7 spec, which sounds like it might be what you're looking for: https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf

**Comment by alexsasharegan** [comment]
This looks like exactly what I was looking for in terms of a spec!!!
