### ISSUE TITLE
template.size() returns fullpage

### ISSUE THREAD

**Issue by RayFinney** [jung-kurt/gofpdf#165]
I'm testing the lib at the moment and i dont know if I make something wrong or what is going on here.
I try to make a invoicy looking position/item table, I tried the "Table"-Example, didnt work so i build something on my own.

I try to calculate the Text YPositions within the ItemBlock(Template) based on the size(height) of the previous ItemBlock(Tempate).

But the ItemBlock size always returns

> {210.00155555555557 297.00008333333335}

```
itemsBlock := pdf.CreateTemplate(func(tpl *gofpdf.Tpl) {

		indexX := borderLeft
		descriptionX := borderLeft+10
		unitPriceX := 120.0
		quantityX := 150.0
		totalX := 170.0

		tpl.Text(indexX, 125, "#")
		tpl.Text(descriptionX, 125, t.Translate("description"))
		tpl.Text(unitPriceX, 125, t.Translate("unit_price"))
		tpl.Text(quantityX, 125, t.Translate("quantity"))
		tpl.Text(totalX, 125, t.Translate("total"))
		tpl.Line(indexX, 127, 200, 126)

		height := 133.0
		for index, item := range document.Items {
			itemBlock := tpl.CreateTemplate(func(tpl2 *gofpdf.Tpl) {
				blockY := height
				price, _ := decimal.NewFromString(item.SellingPrice.Value)
				amountStr := strconv.Itoa(int(item.Amount))
				tpl2.Text(quantityX, blockY, amountStr)
				amount, _ := decimal.NewFromString(amountStr)

				tpl2.Text(indexX, blockY, fmt.Sprintf("#%d",index+1))

				tpl.SetFont("helvetica", "B", 10)
				tpl2.Text(descriptionX, blockY, item.Name)
				tpl.SetFont("helvetica", "", 10)
				tpl2.Text(unitPriceX, blockY, fmt.Sprintf("%s %s", price.StringFixed(2), item.SellingPrice.Currency))
				tpl2.Text(totalX, blockY, fmt.Sprintf("%s %s", price.Mul(amount).StringFixed(2), item.SellingPrice.Currency))
				log.Println(tpl2.GetXY())
			})
			_, itemBlockSize := itemBlock.Size()
			log.Println(itemBlockSize)
			height += itemBlockSize.Ht
			tpl.UseTemplate(itemBlock)
		}
	})
```

**Comment by jung-kurt** [comment]
> I try to make a invoicy looking position/item table, I tried the "Table"-Example, didnt work so i build something on my own.

All examples run as part of the project test. If `go test` succeeds then the table examples run properly.

I'll defer comments about the template to @marcus-downing, the author of the templating functionality. But at first glance, you get the results I would expect. A subtemplate is repeatedly created with the same format and repeatedly, and predictably, reports the same size as the other subtemplates.

I would seriously question the need to create templates and subtemplates in a loop. The idea is to create them once and use them multiple times.

**Comment by marcus-downing** [comment]
[As it says in the docs](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.CreateTemplate):

> CreateTemplate defines a new template using the current page size.

> CreateTemplateCustom starts a template, using the given bounds.

So if you need a template with a different size, use CreateTemplateCustom and feed it the template size you need. This does sadly mean that you need to know the rendered object's size in advance. If you need more advanced templating functionality, you can implement the `Template` interface.

This is a direct equivalent of the FPDF_Tpl functionality it was ported from.

**Comment by marcus-downing** [comment]
There's also a `CreateTemplate` function that isn't a method of an existing Fpdf. That also need a size in advance.

**Comment by RayFinney** [comment]
Sry for the late response.
Thanks for your help, i kinda missed the part where it says 

> CreateTemplate defines a new template using the current page size.

I managed to get a CellFormat-Table but man is PDF a pain in the a** positioning and line-break is kinda impossible if you need to keep it somewhat dynamic.

This was clearly a user-issue so can be closed.
