### ISSUE TITLE
Write doesn't honor line breaks

### ISSUE THREAD

**Issue by bennesp** [jung-kurt/gofpdf#167]
The documentation states: 

> Write prints text from the current position. When the right margin is reached (or the \n character is met) a line break occurs and text continues from the left margin.

Apparently, either I am making some errors, or the function Write() doesn't automatically create line breaks

This is the code
```go
func main() {
	pdf := gofpdf.New("P", "pt", "A4", "")
	pdf.SetMargins(100, 100, 100)
	pdf.SetFont("Courier", "", 12)
	pdf.SetAutoPageBreak(true, 0)
	pdf.AddPage()
	for i := 0; i < 100; i++ {
		pdf.Write(0, strconv.Itoa(i))
	}
	err := pdf.OutputFileAndClose("hello.pdf")
	if err != nil {
		fmt.Println(err)
	}
}
```

And this is the result
<img width="794" alt="schermata 2018-03-14 alle 23 36 24" src="https://user-images.githubusercontent.com/5445545/37434675-a4028366-27e0-11e8-941f-015f360a47b5.png">

**Comment by jung-kurt** [comment]
The `write`() method (which is called by `Write`()) will break on the most recently encountered space character. This behavior (word wrapping) is not correctly described in the documentation. I think the right behavior on reaching the right margin would be to break on the most recent whitespace on the current line, and if there is none, to break on the most recent character. That would preserve the expected word wrapping behavior and also handle the edge case that you demonstrate.

I'll tag this as a bug. Thanks for reporting.

**Comment by bennesp** [comment]
Thanks for the reply
However I edited my for loop, adding a Write() to insert the space character, and the result remains the same. Maybe I'm doing something wrong (maybe the first argument zero is wrong?).

```go
for i := 0; i < 100; i++ {
	pdf.Write(0, strconv.Itoa(i))
	pdf.Write(0, " ")
}
```

Sorry but I can't find any example about how to use the Write function with something like automatic line breaks. Maybe it just can't be done, maybe I'm doing something wrong

**Comment by jung-kurt** [comment]
On closer inspection, your original code is working as documented. But you specified a line height of zero, so the subsequent lines just overwrote themselves.

Try this:

```go
package main

import (
        "fmt"
        "strconv"
        "github.com/jung-kurt/gofpdf"
)

func main() {
        const lineHt = 14
        pdf := gofpdf.New("P", "pt", "A4", "")
        pdf.SetMargins(100, 100, 100)
        pdf.SetFont("Courier", "", pdf.UnitToPointConvert(lineHt))
        pdf.SetAutoPageBreak(true, 0)
        pdf.AddPage()
        for i := 0; i < 100; i++ {
                pdf.Write(lineHt, strconv.Itoa(i))
        }
        err := pdf.OutputFileAndClose("hello.pdf")
        if err != nil {
                fmt.Println(err)
        }
}
```

**Comment by bennesp** [comment]
Yes it works, thank you so much!
