### ISSUE TITLE
Setting font size in units

### ISSUE THREAD

**Issue by stanim** [jung-kurt/gofpdf#17]
SetFontSize is confusing as it uses points, where all other drawing operations use the unit size. Right now it is not straightforward to set the font size in units, as the scale factor f.k is private. It feels quite clumsy to calculate it first with eg. GetFontSize

We can't touch anymore SetFontSize for backwards compatibilty, but we could solve it in these ways:

1. Expose f.k as a f.Unit2Point field
2. Define a SetFontUnitSize method
3. Define a UnitToPoint method (and maybe PointToUnit)
4. ... (I'm open for better solutions)

I think 1 has my preference as it is more generally useful and has the least impact. I can do a pull request when an agreement is reached.

**Comment by marcusatbang** [comment]
I'm in favour of making sensible utility methods available (see eg [some methods added in my branch to aid with orientation and scale](https://github.com/marcusatbang/gofpdf/commit/db924decfbe9dd0a659341022f414481b7e98dc6)) simply because DRY, but that doesn't mean Kurt shouldn't add a `SetFontUnitSize` method as well.

**Comment by jung-kurt** [comment]
[PointConvert()](http://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.PointConvert) can help in this regard. It is used in several of the examples. I'll make sure it gets referenced in the `SetFontSize` documentation.

**Comment by jung-kurt** [comment]
I like the idea of a `SetFontUnitSize` -- I'll take care of that.

**Comment by stanim** [comment]
@jung-kurt I saw PointConvert(point->unit), but what is needed in this case is UnitConvert(unit->point), which doesn't exist

**Comment by jung-kurt** [comment]
I'll add both `SetFontUnitSize` and `UnitConvert`.

**Comment by stanim** [comment]
Great!

**Comment by jung-kurt** [comment]
I just committed these changes. See `UnitToPointConvert` and `SetFontUnitSize`.
