### ISSUE TITLE
AutoPageBreak doesn't respect pdf.SetMargins or pdf.SetTopMargin

### ISSUE THREAD

**Issue by nadilas** [jung-kurt/gofpdf#174]
Hello,

When my table requires a page-break, the new page starts with the default margins (1cm) and doesn't respect the values I set in the `pdf.SetMargin` or `pdf.SetTopMargin`.

In the `CellFormat` I can't see any reference to querying the margins, it simply applies the pagebreak, but I would expect the `AddPageFormat` method to retrieve the margins and apply them accordingly.

**Comment by jung-kurt** [comment]
`CellFormat()` calls `AddPageFormat()` that in turn calls `beginpage()` that consults `f.tMargin`, the value that is set by `SetMargin()` and `SetTopMargin()`. I'm not sure where that value is being lost. Is this problem occurring only with tables?

**Comment by nadilas** [comment]
It happens in general.
It's confusing, becuase the value doesn't get lost. On line `fpdf.go:2795` I can see the topMargin being applied:
`f.y = f.tMargin`

After my headerFunc being applied. It seems the `f.y` is not reset to the topMargin. Well I can do that manually, but would have expected the `f.y = f.tMargin` to be applied again after the `headerFunc` being called. 

Does this help?

**Comment by nadilas** [comment]
Maybe you'll see what the problem is. Here's my headerFunc:

```go
drawCompanyHeaderPath := func() {
		pdf.SetDrawColor()
		pdf.SetFillColor()
		pdf.MoveTo()
		pdf.LineTo()
		pdf.LineTo()
		pdf.LineTo()
		pdf.MoveTo()
		pdf.ClosePath()
		pdf.DrawPath()
		pdf.SetDrawColor()
		pdf.SetLineWidth()
		pdf.Line() // left
		pdf.SetLineWidth()
		pdf.Line() // middle
		pdf.Line() // right circle-bottom
		pdf.Line() // right circle-top-right
		pdf.Line() // right circle-top-left
		pdf.SetFillColor()
		pdf.Circle() // circle
}

	pdf.SetHeaderFunc(func() {
		drawCompanyHeaderPath(pdf)

		pdf.Image("comp_logo_rgb.png", 167.8,5.6, 30, 13, false, "", 0, "")

		// draw title
		pdf.SetFont("SourceSansPro", "", 22)
		pdf.Text(25, 12.3, "Document Title")
		pdf.SetFont("SourceSansPro", "", 12)
		pdf.Text(25,16.8, "Subtitle")

		// set document start for autopagebreak
		_, t, _, _ := pdf.GetMargins()
		pdf.SetY(t) // reset to margin
	})
```

**Comment by jung-kurt** [comment]
Everything looks good to me. It might be time to use [delve](https://github.com/derekparker/delve) to see what could be changing the value of f.tMargin. (I haven't used delve before, but it looks very capable.)

**Comment by nadilas** [comment]
I’d like to point out, that the value which I would be looking at would be: f.y

I think after the headerFunc is ran, f.y is changed via one of the commands which I used in my headerFunc and the new page continues from there on.

**Comment by nadilas** [comment]
Sounds great! Provided the user/developer thinks about it. From a library point of view, I’d appreciate if after the header being drawn the .y would be reset automatically, so I don’t have to think about it. Maybe you can call the same ToTopMargin() method after the headerFunc in beginpage()?

**Comment by nadilas** [comment]
Thank you! ;)
