### ISSUE TITLE
Creating Report Sections

### ISSUE THREAD

**Issue by eurosoll** [jung-kurt/gofpdf#175]
Hi

Coming from the php version, I was wondering if there is a relatively simple way to create report sections?

For example a report layout might be:

Report Header
Page Header

Section Header(s)
Detail
Section Break Footer(s)

Page Footer
Report Footer

In php I had some complicated code to try and work out where sections should begin on a page, print at the bottom of pages, minimum heights etc...

I was wondering if there is a simpler way to create this sort of functionality in gofpdf?

Any help or pointers would be appreciated.

Thanks

**Comment by jung-kurt** [comment]
gofpdf is limited in this regard. [`SetAcceptPageBreakFunc()`](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.SetAcceptPageBreakFunc) can help with page header and footer management, and [`SplitLines()`](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.SplitLines) may be useful to determine if a page break is warranted or not. Beyond that, you may find it useful to write some closures like `sectionBegin()` and `footer()` to help with your particular format.

In the process of doing this, if you find some general patterns that could be generally useful please consider adding it gofpdf.

**Comment by eurosoll** [comment]
Thanks for the reply.

I am looking through my old code and looking to rework it and I will definitely look into pasting some ideas.
