### ISSUE TITLE
Placing images at -x

### ISSUE THREAD

**Issue by ajstarks** [jung-kurt/gofpdf#178]
The Image method uses the current point of x if x is negative.    (the relevant code is in imageOut (lines 2467-2469)

```
        if x < 0 {
                x = f.x
        }
```

Is this correct? This leads to odd behavior if you want to place an image where some portion is off the canvas.  

Is there an alternative method?

**Comment by jung-kurt** [comment]
That's documented in [`ImageOptions()`](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.ImageOptions) which calls `imageOut()`:

> If x is negative, the current abscissa is used.

Maybe we could put in a bool named "AllowNegativePosition" into the [ImageOptions](https://godoc.org/github.com/jung-kurt/gofpdf#ImageOptions) structure that would be used to optionally skip that coercion.

**Comment by ajstarks** [comment]
Yes, I saw the documentation, I was wondering about the rationale for the coercion.  Is there a use case for it?

An bool  in ImageOptions would be most welcome.

**Comment by jung-kurt** [comment]
Likely the author of the original [fpdf library](http://www.fpdf.org/), from which gofdpf is ported, didn't think negative positions for images made sense, and that using a negative number for x could be a convenient replacement for having to pass `pdf.GetX()`.

I'll put in the boolean when I get a chance.

**Comment by jung-kurt** [comment]
Done. See example at [pdf.ImageOptions](https://godoc.org/github.com/jung-kurt/gofpdf#example-Fpdf-ImageOptions).

**Comment by ajstarks** [comment]
Wonderful, thank you.
