### ISSUE TITLE
Pdf Margins and ImageOptions.

### ISSUE THREAD

**Issue by avb-qlik** [jung-kurt/gofpdf#179]
I would expect that the image drawing (in raw bytes) with `ImageOptions` respects the pdf margins set like this `pdf.SetMargins(margin.Left, margin.Top, margin.Right)`, but it's not.

Example:
```
       // suppose margins in inches
       // margins left and top are 1.4in
       pdf.SetMargins(1.4, 1.4, 0)
       
       options := gofpdf.ImageOptions{
		ReadDpi:   true,
		ImageType: "PNG",
	}

       reader := bytes.NewReader(rawBytes)
       tc.pdf.RegisterImageOptionsReader("imageName", options, reader)

       // the image size is 3in x 3in
       tc.pdf.ImageOptions(name, 0, 0, 3, 3, false, options, 0, "")
```

then the image is placed at `(x,y)=(0,0)` and not in `(1.4,1.4)`.
How does it work ? 

Thanks

**Comment by jung-kurt** [comment]
Margins are used only for text wrapping and alignment purposes. The current position, whether explicitly set with `SetXY()` and friends or implicitly set with methods like `ImageOptions()`, is not constrained by the current margins. If you want to place an image next to the margins, you will need to use something like

```go
lf, tp, _, _ := tc.pdf.GetMargins()
tc.pdf.ImageOptions(name, lf, tp, 3, 3, false, options, 0, "")
```

**Comment by avb-qlik** [comment]
I see. And what about right and bottom margins ? 
Suppose that you have an image that goes outside the pdf page size (width or height) and you want a right/bottom white margin (I expect to get a right/bottom cropped image), how can I do that? 
I guess that applying margins to width and height will stretch the image.
e.g.
```
lf, tp, r, _ := tc.pdf.GetMargins()
tc.pdf.ImageOptions(name, lf, tp, 3 - r, 3, false, options, 0, "")
```

**Comment by jung-kurt** [comment]
I don't believe it is possible to have gofpdf crop an image, but it will scale one for you. If you want to have an image that goes from the left margin to the right (with white margins preserved), you would call `ImageOptions()` as follows:
```go
lf, tp, rt, bt := tc.pdf.GetMargins()
tc.pdf.ImageOptions(name, lf, tp, rt - lf, 0, false, options, 0, "")
```
When you specify 0 for the image height, you tell `ImageOptions()` to adjust the height so that the image's aspect ratio is maintained. If the image is too tall when you do this, then you would constrain the height rather than the width:
```go
lf, tp, rt, bt := tc.pdf.GetMargins()
tc.pdf.ImageOptions(name, lf, tp, 0, bt - tp, false, options, 0, "")
```

**Comment by avb-qlik** [comment]
OK. I will play on it. Thanks.
