### ISSUE TITLE
Expose f.out

### ISSUE THREAD

**Issue by stanim** [jung-kurt/gofpdf#18]
I need to write custom complex shapes to fpdf. Unfortunately these are not generally usable and would otherwise bloat the api by adding methods. Also it useful if you want to redraw multiple times a path, which was generated by a cpu intensive and long running algorithm.

So I need to write directly to the stream when fpdf is imported in another package. I'd like to see f.out exposed as e.g. f.Stream/f.Write/... with a disclaimer that is only for low level access in its docstring. If this is not possible I have to fork the package which I would like to avoid.

**Comment by marcusatbang** [comment]
> Also it useful if you want to redraw multiple times a path, which was generated by a cpu intensive and long running algorithm.

Sounds like you'd benefit from [my branch](https://github.com/marcusatbang/gofpdf), which add templating so you can define a shape once and use it multiple times. I fully intend to submit a pull request when I can find time to get it ready.

**Comment by jung-kurt** [comment]
Templating will be a valuable feature.

Aside from that, I'll export a wrapper to out(). Maybe it can function only if "unsafe" mode has been set.

**Comment by stanim** [comment]
Thanks for the wrapper! That is very important for me. Maybe fpdf.Raw() is a good name for the wrapper.

**Comment by jung-kurt** [comment]
I just committed `RawWriteStr` and `RawWriteBuf`.
