### ISSUE TITLE
code pages for Myanmar3.ttf

### ISSUE THREAD

**Issue by alexaung** [jung-kurt/gofpdf#180]
Hi,

I have the Unicode Character Map for Myanmar3 as follow 
https://everythingfonts.com/unicode/myanmmar

I am trying to create custom code page but it is not working. 
Could you please let me know how to create a code page file for this unicode font.

Regards,
Alex

**Comment by jung-kurt** [comment]
Unfortunately, you've encountered gofpdf's biggest limitation, namely, its lack of support for fonts with more than 256 glyphs. You'll have better luck with [gopdf](https://github.com/signintech/gopdf), which supports Unicode fonts.
