### ISSUE TITLE
Rotate text (not page)

### ISSUE THREAD

**Issue by tj-kev** [jung-kurt/gofpdf#183]
I'm trying to rotate text using the following code:

```
    pdf.TransformBegin()
    pdf.TransformRotate(90, 0, 0)
    pdf.CellFormat(40, 10, "my text", "", 0, "C", false, 0, "")
    pdf.TransformEnd()
```
This is in multiple locations on the page.

Should transformations be taken independently between each transform begin and end? Looks like it is rendering all the cells and then applying the transformation as one. Rotating the entire page instead of each cell independently?

Is there a way to achieve this?

**Comment by jung-kurt** [comment]
> Looks like it is rendering all the cells and then applying the transformation as one. Rotating the entire page instead of each cell independently?

This result surprises me. The PDF generated by [this example](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.TransformBegin) transforms only the content generated between TransformBegin() and TransformEnd().

**Comment by tj-kev** [comment]
Its ok, my bad.

Some confusion with the x,y. Great library btw!
