### ISSUE TITLE
How to add image with size in px?

### ISSUE THREAD

**Issue by bohdanlisovskyi** [jung-kurt/gofpdf#184]

**Comment by jung-kurt** [comment]
In a PDF file, you can't specify the image size in pixels for pretty much the same reason you can't specify a print size in your camera. What might look good on a computer screen could be miniscule on a printed page. You can look into [`SetDpi()`](https://godoc.org/github.com/jung-kurt/gofpdf#ImageInfoType.SetDpi) if you need to control image resolution.
