### ISSUE TITLE
Is it possible to make a checkmark inside pdf?

### ISSUE THREAD

**Issue by devEntrega** [jung-kurt/gofpdf#188]
Like this 
Picture:
![imagen](https://user-images.githubusercontent.com/35384990/44108538-585330d4-9fc0-11e8-96c0-99670ed6b9be.png)

If so, how do I do that?

Thanks for your time.

**Comment by jung-kurt** [comment]
Interactive checkboxes are not supported since this library can be used only to generate static PDFs. If you only need a non-interactive checkmark, you could try calling SetFont() with "ZapfDingbats" as the font family name. See [https://en.wikipedia.org/wiki/Zapf_Dingbats]() for a chart of glyphs.
