### ISSUE TITLE
README should provide more information.

### ISSUE THREAD

**Issue by stanim** [jung-kurt/gofpdf#19]
"For every hour of code you write, spend an hour writing your README"
https://medium.com/@cwRichardKim/how-to-get-hundreds-of-stars-on-your-github-project-345b065e20a2

I know that the godoc documentation provides this, but I'm afraid that visitors quickly exploring many repositories on github do not click on the link. It is also much more easy to star the project if the README convinces you.

If you want, I can prepare a pull request.

**Comment by jung-kurt** [comment]
Point well taken.

A few days ago, I came across a [command](https://github.com/JImmyFrasche/autoreadme) that generates formatted README files from Go documentation. This may be the most convenient way of keeping the project page up-to-date with the documentation.

**Comment by stanim** [comment]
Ok, I leave you experimenting with the autoreadme.

**Comment by jung-kurt** [comment]
The autoreadme utility can make a README file from a template. This way, some information can be put in the README that doesn't necessarily belong in the documentation. 

Feel free to make adjustments to either that you think will improve the package.

**Comment by jung-kurt** [comment]
Unfortunately, some formatting constructions that look good in Markdown look pretty bad in the godoc presentation, for example, bulleted lists and hyperlinks. I might fuss with a little post-autoreadme processing using sed to address this.

**Comment by stanim** [comment]
Talking about README... My gofpdf backend has been merged in the draw2d package . So now with exactly the same code you can draw to a bitmap image and to a pdf document: https://github.com/llgcode/draw2d.samples. That is how I started contributing to gofpdf in the first place.

In the README of draw2d I've put a link to gofpdf. Would you be willing to reference the draw2d package in some way (https://github.com/llgcode/draw2d)?

**Comment by jung-kurt** [comment]
Nice work on the draw2d library!

I've rearranged the README to flow a bit better.

**Comment by stanim** [comment]
Much better now! Thanks for mentioning draw2d.
Op 10 jul. 2015 04:02 schreef "Kurt Jung" <notifications@github.com>:
