### ISSUE TITLE
Add new line into table cell

### ISSUE THREAD

**Issue by Raggaer** [jung-kurt/gofpdf#198]
I am currently trying to make a calendar table into a PDF, I currently can render a calendar, however I would like to add events on certain days...

Currently I am using `CellFormat` but when I add an event the text will overflow outside (since `CellFormat` does not work with `\n`). I tried using `MultiCell` but this approach adds each cell that contains events into a newline...

Is there something I can do to use `MultiCell` but then continue on the same line (for the next cell) instead of writing the next cell on a new line?

Or is there something else I can use to make use of `\n` for the `CellFormat` function?

**Comment by jung-kurt** [comment]
In fpdf_test.go, the function [`ExampleFpdf_Rect()`](https://godoc.org/github.com/jung-kurt/gofpdf#example-Fpdf-Rect) demonstrates line wrapping in a table cell. Does the technique work for your particular use case?

**Comment by Raggaer** [comment]
Thanks, while this option worked I opted to use an approach using `CellFormat` and adding extra cells for all rows (if theres a calendar event that week)

Thanks for the answer
