### ISSUE TITLE
Cell after MultiCell

### ISSUE THREAD

**Issue by tylerzika** [jung-kurt/gofpdf#201]
I'm trying to achieve this:
<img width="355" alt="screen shot 2018-10-19 at 12 40 00 am" src="https://user-images.githubusercontent.com/1011888/47204221-a6ce4c80-d337-11e8-9d37-7ab170c8502b.png">
"INJECT ONE" all the way to "FOR" is a MultiCell. "REFILLS" is another cell. This is my code:

```go
// #7 SIG
label.MultiCell(3, .2, prescription.SIGExpanded, "", "", false)

//20. Refills Remaining and #17 Expiration Date - Bold
label.Cell(4, .1, "REFILLS: "+fmt.Sprintf("%.3f", prescription.RefillsLeft)+" BY "+formatDateYearMonthDay(prescription.ExpirationDate, "Expiration Date"))
```
But the output is this:
<img width="744" alt="screen shot 2018-10-19 at 12 43 49 am" src="https://user-images.githubusercontent.com/1011888/47204411-16443c00-d338-11e8-9bcc-73c00cf981e7.png">

How to I move "REFILLS" to the right of the MultiCell, under "DAY SUPPLY"?

**Comment by jung-kurt** [comment]
The example looks like two adjacent MultiCells. In the left box, the words wrap automatically. In the right box, you can use newlines ("\n") to control the lines.

**Comment by jung-kurt** [comment]
@tylerzika, please reopen if using two adjacent cells does not solve problem.

**Comment by tylerzika** [comment]
@jung-kurt but both my left MultiCell and my right MultiCell use variables. How can I use newlines with a variable? The length of the variable can vary in length.

**Comment by tylerzika** [comment]
actually `MoveTo()` is solving all my problems! Great function!!

**Comment by jung-kurt** [comment]
> actually MoveTo() is solving all my problems!

Super!
