### ISSUE TITLE
How to add png image file?

### ISSUE THREAD

**Issue by dealwd** [jung-kurt/gofpdf#202]
First I generate barcode. Then I need add this barcode to pdf. How to do that? I use **"github.com/boombuler/barcode"** for generate barcode.

    myCode, _ := code128.EncodeWithoutChecksum("sdsdsd39478234234")
    myCode, _ = barcode.Scale(myCode, 1500, 500)
    file, _ := os.Create("barcode.png")
    defer file.Close()
    png.Encode(file, myCode)

**Comment by pitw** [comment]
Had exactly same question with boombuler/barcode.
Fortunately theres already a contrib for barcodes - even with same lib.

Check here:
https://godoc.org/github.com/jung-kurt/gofpdf/contrib/barcode

Or some examples in tests:
https://github.com/jung-kurt/gofpdf/blob/master/contrib/barcode/barcode_test.go
