### ISSUE TITLE
Template placed wrong

### ISSUE THREAD

**Issue by d1ngd0** [jung-kurt/gofpdf#203]
Running the following code you would expect a border of 2 inches all along the outside of the pdf document

```go
package main

import (
	"os"

	"github.com/d1ngd0/gofpdf"
)

func main() {
	pdf := gofpdf.New("P", "in", "", "")
	tpl := pdf.CreateTemplateCustom(
		gofpdf.PointType{X: 0, Y: 0},
		gofpdf.SizeType{Wd: 18, Ht: 10}, func(t *gofpdf.Tpl) {
			t.SetLineWidth(2)
			t.Rect(0, 0, 18, 10, "")
		})

	pdf.AddPageFormat("P", gofpdf.SizeType{Wd: 18, Ht: 10})
	pdf.UseTemplateScaled(tpl, gofpdf.PointType{X: 0, Y: 0},
		gofpdf.SizeType{Wd: 18, Ht: 10})

	pdf.Output(os.Stdout)
}
```

Instead you get the box rendered at an offest of Ht - Wd... so although Y is set to 0 it renders at -8

**Comment by jung-kurt** [comment]
You have definitely uncovered something odd. The simplest case works as expected:
```go
package main

import (
	"os"

	"github.com/jung-kurt/gofpdf"
)

func main() {
	pdf := gofpdf.New("P", "in", "Letter", "")
	pdf.AddPage()
	tpl := pdf.CreateTemplate(func(t *gofpdf.Tpl) {
		t.SetLineWidth(.01)
		t.Rect(1, 1, 6.5, 9, "")
	})
	pdf.UseTemplate(tpl)
	pdf.Output(os.Stdout)
}
```
The combination of a custom page and scaled template application seems to introduce the problem.

Did you determine that the offset is `Ht - Wd` from the code?

**Comment by d1ngd0** [comment]
I came to the conclusion after testing multiple sizes. Interestingly the problem doesn't appear when the height is greater than the width. Only when the width is greater than the height.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by d1ngd0** [comment]
Just so you are aware, When I changed letter to have a larger width than height
```go
	f.stdPageSizes["letter"] = SizeType{792, 612}
```

The simple implemention above fails as well. (obviously changing the size of the box drawn)

```go
package main

import (
	"os"

	"github.com/jung-kurt/gofpdf"
)

func main() {
	pdf := gofpdf.New("P", "in", "Letter", "")
	pdf.AddPage()
	tpl := pdf.CreateTemplate(func(t *gofpdf.Tpl) {
		t.SetLineWidth(.01)
		t.Rect(1, 1, 9, 6.5, "")
	})
	pdf.UseTemplate(tpl)
	pdf.Output(os.Stdout)
}
```

**Comment by d1ngd0** [comment]
I believe I found the issue. It occurs when a new template is create
```
	orientationStr := "p"
	if size.Wd > size.Ht {
		orientationStr = "l"
	}
	sizeStr := ""
```

This switches the orientation based on the width and height, although it is not an illegal operation to create a larger width than height and have an orientation of P.

I will work on a solution.

**Comment by d1ngd0** [comment]
#207 Added
