### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by zaheer6034** [jung-kurt/gofpdf#206]
I am using httpimg.Register method to register a url of image. 
Like this `httpimg.Register(pdf, image_link, "")`
I have a json with different image url's, when I loop on all the urls and map them and register using httpimg.Register the url's and then embed the image in my pdf I came across an issue. The problem is there is possibility that url is broken (i.e image doesn't doesn;t exist in some urls ) and because of this issue my program halts the pdf generation and at the end pdf doesn;t generates. I want to handle this error i.e if url is broken then i want to add any empty image etc.
I am confused how to handle this error, please review my code and guide me.
   
x := 0.0
		y := 0.0
		col := 0
var img_len int = len(img.Images.Photos)
for i :=0; i<img_len; i++ {
			image_link := b[i].Images
			pic_link := b[i].Link
			println("image link",image_link)
			httpimg.Register(pdf, image_link, "")
if col == 5{	
			x = 0.0
			y += 40.0
			col = 0
			pdf.Ln(3)
			}
pdf.Image(image_link, 20+x, 30+y, 30, 30, false, "", 0, pic_link)
			pdf.Cell(10, 0, "")
			col += 1
			x += 35.0

**Comment by jung-kurt** [comment]
You will want to use [`pdf.Error()`](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.Error), [`pdf.ClearError()`](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.ClearError) and friends. For example,
```go
httpimg.Register(pdf, image_link, "")
if pdf.Err() {
  log.Printf("error registering image %s: %s", image_link, pdf.Error())
  pdf.ClearError()
}
```

**Comment by zaheer6034** [comment]
Thankyou very much for your response. It really helped me alot 👍

**Comment by jung-kurt** [comment]
Glad that worked.
