### ISSUE TITLE
The Content in pdf is not in center. It by default is left aligned.

### ISSUE THREAD

**Issue by SanjayMW** [jung-kurt/gofpdf#211]
I want to export an excel file data in PDF. The data in the excel table is left aligned. Can you please help me to make it center aligned. 
I have attached a downloadable link for it as well. 
[report.pdf](https://github.com/jung-kurt/gofpdf/files/2594463/report.pdf)

**Comment by SanjayMW** [comment]
Actually my question was not clear, I want to have the whole table in the center,not the data in the table.

**Comment by jung-kurt** [comment]
> I want to have the whole table in the center

Set the X position of the start of each row to one half of (full page width - table width). I have updated the [tables example](https://godoc.org/github.com/jung-kurt/gofpdf#example-Fpdf-CellFormat-Tables) to illustrate this.

**Comment by jung-kurt** [comment]
Please reopen this issue if the previous advice didn't work for you.
