### ISSUE TITLE
Multicell in Template

### ISSUE THREAD

**Issue by d1ngd0** [jung-kurt/gofpdf#215]
When in a template and using `AutoSetPageBreak(true, 0)` the template will only render the last page within the template. I am fully aware that the Tpl isn't intended to add new pages, so this isn't really a bug, however I would like to know if you put any thought into making it allow pages and any ideas you may have before I try tackling it.

Thanks!

**Comment by jung-kurt** [comment]
Thanks for bringing this up. I wish @marcus-downing was still actively involved with this project or at least available to offer some suggestions.

**Comment by marcus-downing** [comment]
Sorry...

The templates work as a sort of stamp: a group of elements that you add to a page, potentially with other elements such as a header/footer, background, overlay etc. If they flowed across multiple pages, you'd need to consider how and whether to duplicate elements. It sounds like what you need isn't so much a template as sub-document that can be slipped wholesale into one or more larger documents.

I can imagine adding a core function `func (f *Fpdf) InsertPagesFrom(source *Fpdf, firstPage, numPages int)` that dumped pages (and any associated images, templates, fonts etc) from a source document into the current document.

However, that functionality would likely run into the same unsolved problem with templates: font subsetting. When combining two documents that contain subsets of the same font, they should ideally notice this, merge the subsets then cut a new subset serving the pages in the new document. That's a big piece of work. And as with templates, one you can get away without doing... most of the time.

**Comment by jung-kurt** [comment]
Good to hear from you, @marcus-downing -- thanks for your comments.

**Comment by d1ngd0** [comment]
#216 Added the ability to extract templates by pagenumber from a template. @marcus-downing I would love it if you could look into this, as I don't have a complete understanding of the underlying mechanisms that enable the template feature. Hopefully this solution isn't too horrid.

If I'm given the green light by the two of you I will invest some time in making propery unit tests for this new feature.

**Comment by marcus-downing** [comment]
That looks pretty good, actually.

- If I'm following it, the current behaviour of the `Bytes()` method is preserved because you use the template's internal page number.
- Is counting pages from 1 the convention throughout gofpdf? If so, a single empty `byte[]` is a small price to pay for making that work.
- Needs a comment on the `FromPages()` method.

It doesn't address the question of framing the template on the outside, ie headers and so on, but I guess it's up to the person composing the outer document to make that decision.

**Comment by jung-kurt** [comment]
Nice work, @d1ngd0, and thanks for your remarks, @marcus-downing.

> Is counting pages from 1 the convention throughout gofpdf?

Yes. The internal page number starts at zero and is incremented with each new page.

**Comment by jung-kurt** [comment]
> Needs a comment on the FromPages() method.

The command line helpers `./check` and `./cov` should be run before committing. Sometimes I remember to actually do this.

**Comment by d1ngd0** [comment]
I will invest some time into this in the next few days, adding comments, unit tests, etc.... I'll remove my pull request as well and make a new one so everything is in the same commit

**Comment by jung-kurt** [comment]
Excellent. I look forward to including your changes, @d1ngd0.

**Comment by marcus-downing** [comment]
> I'll remove my pull request as well and make a new one so everything is in the same commit

That shouldn't be necessary, if you just rebase and force-push to the same branch.

**Comment by d1ngd0** [comment]
Yes, I was planning on adding some unit tests.

**Comment by d1ngd0** [comment]
Alright, Updated the comments, and created a testcase for it. I also squashed everything so we should be good to go?

**Comment by jung-kurt** [comment]
Thanks, @d1ngd0 -- merged with ec1d4b07b1a618f55f4a229ef08b72e02b032228
