### ISSUE TITLE
Decode Bug

### ISSUE THREAD

**Issue by d1ngd0** [jung-kurt/gofpdf#218]
I realized last night that I introduced a bug with the addition of Encoding and Decoding templates. When a template is created it is given an ID by the GenerateTemplateID method. This worked in the past because a template could not exist outside the context of it's original gofpdf package. However now that templates can be saved to files, or templates can be generated across a cluster of machines maintaining the original ID for a template will quickly create Template ID conflicts where many Templates claim to have an ID of 1. I'll start working on a PR to fix this, but figured I should bring it to your attention.

Thanks!

**Comment by jung-kurt** [comment]
Good catch. Can a unique ID be assigned when the stored template is loaded?

**Comment by d1ngd0** [comment]
That was my plan, I am going to keep the solution limited to the Encode and Decode functions. Essentially strip away the template id when encoding, and add a new one back in when decoding. Then we won't have clashing anymore.

**Comment by d1ngd0** [comment]
https://github.com/d1ngd0/gofpdf/commit/a94a239047daf957e399870de0ba56ef69dcc702

@jung-kurt and @marcus-downing (sorry to call on you again) hopefully you can give me a little insight here because from the standpoint of the Template this should work. I added the example go program to illustrate how this doesn't work, though obviously the PR won't have that in there...

What I am seeing right now is that images in the parent template will show, however images any deeper do not. If I change the Encode and Decode methods to maintain the templates ID the images in children templates appear again. I am starting to worry that the Template ID is referenced somewhere within bytes. Any help would be appreciated.

**Comment by d1ngd0** [comment]
Also, I was curious if the ID had to be a number? I changed it to a string locally and the pdf still rendered. I'm just curious if that is valid. If so would it make sense to have a default Template generator function, but allow the user to supply their own Template generator? That way people could use whatever id generation library they wanted without trying to build one internally or pulling in a dependency of some kind.

**Comment by marcus-downing** [comment]
A string or struct would provide a way of namespacing images to avoid any risk of a clash. They could then be flattened to something else on PDF output.

```go
type imageID struct {
    templateID int64,
    imageID int64
}
```

**Comment by marcus-downing** [comment]
I'm pretty certain that template ID is not output anywhere in the resulting PDF.

**Comment by marcus-downing** [comment]
And immediately after posting that, I saw that I was wrong 😄

**Comment by marcus-downing** [comment]
However, `GenerateTemplateID` is global (and thread safe, since it's channel based), so even if you use templates inside templates, it'll never have a clash of template ID.

**Comment by d1ngd0** [comment]
Alright, I did some additional research on named objects and found that changing the id to a string won't stop the pdf from being valid. I have put some more work into a solution and would love to hear what you both think. I have added a prefix to the id, if you don't add a prefix the template id structure will remain the same as before.

https://github.com/d1ngd0/gofpdf/commit/8bc0bd27bc4456444485071164b8b42bd050f1bd

**Comment by d1ngd0** [comment]
Actually, after thinking about this. Couldn't we just make the ID method return the sha1 sum of the Bytes method?

**Comment by jung-kurt** [comment]
> Actually, after thinking about this. Couldn't we just make the ID method return the sha1 sum of the Bytes method?

Great idea!

**Comment by jung-kurt** [comment]
Committed: 580543bbbf6ba6a65b8aa9cdbf7d15069d651cb5

**Comment by d1ngd0** [comment]
Thanks! It looks like fonts might be having the same issue. I am looking into a solution for this as well.

**Comment by d1ngd0** [comment]
#220
This should fix it.
