### ISSUE TITLE
Quick Start example

### ISSUE THREAD

**Issue by stanim** [jung-kurt/gofpdf#22]
Not really an issue, but more a critical question. Would it be not better for an outsider to use `OutputFileAndClose` instead of `Output`? Are people not more interested in quickly generating a pdf file rather than seeing its raw data stream?

**Comment by jung-kurt** [comment]
Good point. I think that example predates the `OutputFileAndClose` function. I've made the change.

**Comment by stanim** [comment]
Thanks.
