### ISSUE TITLE
different hashes for the same file

### ISSUE THREAD

**Issue by FrankIT60** [jung-kurt/gofpdf#226]
Hello,

Even if I always create the same file I get different hashes.
I think that a timestamp or similar mechanism is inserted during the creation of the file.
In case it would be possible to configure this as an option?

For example it would be useful if you want to reproduce a document and be sure it is the same as the original.

Thanks
Franco

**Comment by jung-kurt** [comment]
Please reopen if the timestamp and catalog functions shown above don't solve your problem.
