### ISSUE TITLE
Can't add image with JPG

### ISSUE THREAD

**Issue by devEntrega** [jung-kurt/gofpdf#228]
Just the title says, I can't add picture with JPG format, it appears the error "not a PNG buffer", is JPG format supported or not?

Thanks.

**Comment by jung-kurt** [comment]
JPG images are supported, see [this example](https://godoc.org/github.com/jung-kurt/gofpdf#example-Fpdf-Image). Might your JPG image file have the wrong extension, or the type argument to `Image()` be incorrect?

**Comment by devEntrega** [comment]
> 
> 
> JPG images are supported, see [this example](https://godoc.org/github.com/jung-kurt/gofpdf#example-Fpdf-Image). Might your JPG image file have the wrong extension, or the type argument to `Image()` be incorrect?

I see, now the problem is when I change png to jpg, I get panic error when I try to get ImageInfo, I "register" and same results (nil), with PNG works without problem.

**Comment by jung-kurt** [comment]
Please reopen if this problem can be pinpointed to a bug in gofpdf rather than just an invalid image.
