### ISSUE TITLE
Wrong tag for 2.1.3

### ISSUE THREAD

**Issue by TwinProduction** [jung-kurt/gofpdf#236]
[All releases/versions so far have been prefixed with `v`, but not `2.1.3`.](https://github.com/jung-kurt/gofpdf/releases)

I'm not sure whether this was intentional, but it might cause some annoyance for people using dependency management tools like `dep` as the version format is no longer consistent.

CC: @jung-kurt (you're the only one who can currently create tags)

**Comment by jung-kurt** [comment]
Oops, my fault. Thanks for bringing that to my attention, @TwinProduction.
