### ISSUE TITLE
How to find the baseline of a font?

### ISSUE THREAD

**Issue by stanim** [jung-kurt/gofpdf#24]
GetFontSize returns the total height of the text (from Desc to Asc in picture below), but I need to know the baseline. For example in the text "go" I'd like to know how to calculate the bottom of the "o", not of the "g", is this possible (base in picture below)? I have the feeling this info could be parsed somewhere in the `getInfoFrom*` functions in [font.go](https://github.com/jung-kurt/gofpdf/blob/master/font.go).

![baseline](https://grahamwideman.wikispaces.com/file/view/vertfontmetrics-05-selfbuildtype-hudson-orig.png/441511982/vertfontmetrics-05-selfbuildtype-hudson-orig.png)

**Comment by jung-kurt** [comment]
The following structure comprises all the metrics that are read from a font file:
```
type fontDescType struct {
        Ascent       int 
        Descent      int 
        CapHeight    int 
        Flags        int 
        FontBBox     fontBoxType
        ItalicAngle  int 
        StemV        int 
        MissingWidth int 
}
```
If you can find how to derive the baseline from this structure, we can definitely export it.

Do you happen to know if Adobe publishes the baseline information for the embedded fonts? Do you know how to extract the baseline from TTF or Type 1 fonts?

**Comment by stanim** [comment]
Interesting... I guess this is all we need ... from Pdf 1.3 specification,p.330: 
```
Ascent (number, required) The maximum height above the baseline reached by glyphs
in this font, excluding the height of glyphs for accented characters. 

CapHeight (number, required) The y coordinate of the top of flat capital letters, 
measured from the baseline.

Descent (number, required) The maximum depth below the baseline reached by glyphs
in this font. The value is a negative number.

FontBBox (rectangle, required) A rectangle (see Section 3.8.3, Rectangles), 
expressed in the glyph coordinate system, specifying the font bounding box. 
This is the smallest rectangle enclosing the shape that would result if all of
the glyphs of the font were placed with their origins coincident and then filled.

ItalicAngle (number, required) The angle, expressed in degrees counterclockwise 
from the vertical, of the dominant vertical strokes of the font. (For example, 
the 9-o’clock position is 90 degrees, and the 3-o’clock position is –90 degrees.) 
The value is negative for fonts that slope to the right, as almost all italic fonts do.
...
```
I guess it is the Ascent value we need (mabye CapHeight, but I bet on Ascent). With that we should be able to extract the baseline. I did a test and the accent of the string "plÂ" is floating above the cell. Actually I need all these values, because they are **very** interesting. How about making this type public and Addfont returns a FontDescType?  That would not break backwards compatibility, as right now AddFont returns nothing. Or a method GetFontInfo()?

**Comment by stanim** [comment]
Diving in the code, I found a solution. I am preparing a pull request.

**Comment by jung-kurt** [comment]
Ah -- right when I am working on a solution too!

I'll await your changes. I decided to go with `GetFontInfo()` rather than return the descriptor from `AddFont()` because the information may be useful for core fonts.

**Comment by stanim** [comment]
Ok, we can discuss it here a bit further. I am doubting between:
```go
// GetFontDef returns the font definition.
func (f *Fpdf) GetFontDef(familyStr, styleStr string) FontDefType {
	fontkey := familyStr + styleStr // see AddFontFromReader
	return f.fonts[fontkey]
}
```
and
```go
// GetFontDesc returns the font description.
func (f *Fpdf) GetFontDesc(familyStr, styleStr string) FontDescType {
	fontkey := familyStr + styleStr // see AddFontFromReader
	return f.fonts[fontkey].Desc
}
```
What do you think/prefer?

**Comment by jung-kurt** [comment]
I favor returning the `FontDescType`. There is too much private information in `FontDefType` (like font differences, file sizes, etc). If underline metrics and character widths prove to be important, we can include that in a separate structure.

**Comment by stanim** [comment]
I agree. That is what I was doing BTW. I'll continue working on my pull request.

**Comment by jung-kurt** [comment]
Thanks!

**Comment by stanim** [comment]
Somehow it would be nice if the vertical alignment of CellFormat would support besides "T", "M" or "B" (top, middle, bottom), also baseline ("A", "0" or "S"?) in alignStr, but that would be step 2.

**Comment by jung-kurt** [comment]
Does PDF support that natively or would we need to calculate that?

**Comment by stanim** [comment]
I have to find out.

**Comment by jung-kurt** [comment]
Wouldn't specification of baseline alignment require additional information to `CellFormat()`? Specifically, where in the bounding box would the baseline be placed?

**Comment by stanim** [comment]
I would think that putting the baseline of the font at the bottom of the cell is the only placement which makes sense. The baseline of a font defines an 'alternative bottom' in a way, it contains no relation with the top or the middle of the font. That would keep things simple.

**Comment by jung-kurt** [comment]
Good. That would be a valuable feature.

**Comment by stanim** [comment]
What character would you prefer for vertical baseline alignment? "A", "0" or "S"?

**Comment by jung-kurt** [comment]
Any of these is fine with me. Or maybe '_'?

**Comment by stanim** [comment]
I like "_" a lot, but I am afraid it is maybe not so clear in the documentation. What do you think?

**Comment by jung-kurt** [comment]
That's my take on '0' (zero) too -- I like it but it could be confused with 'O' (letter). Let's just go with 'A' then.
