### ISSUE TITLE
How to Split lines in one cell?    In the below text i pasted is printing in one line because of that the text are missing so i need to split lines ([Manager: 12:35 AM - 12:36 AM] [Cashier: 12:36 AM - 01:00 AM] [Manager: 01:09 AM - 02:10 AM] [Cashier: 03:14 AM - 07:30 AM] [Cashier: 07:37 AM - 12:05 AM])

### ISSUE THREAD

**Issue by pruse2402** [jung-kurt/gofpdf#245]
![issue](https://user-images.githubusercontent.com/48112231/56419906-92a0e300-62b9-11e9-9414-b1be404bc465.png)

**Comment by jung-kurt** [comment]
See the [SplitLines (Tables)](https://godoc.org/github.com/jung-kurt/gofpdf#example-Fpdf-SplitLines-Tables) example.

**Comment by jung-kurt** [comment]
Please reopen if this is still an issue.

**Comment by pruse2402** [comment]
Thanks for your reply. Am not getting  the required  output. I don't know to implement this can someone help me to figure out this issue.

Thanks in advance
