### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by stanim** [jung-kurt/gofpdf#25]
Now we have a test coverage of 82%. It would be good to further increase it. Test coverage is no guarantee, just like golint, go vet, ... but it is just an automated way to increase the quality of the code and to avoid collaboration discussions. Also could we take as a condition for merging that the coverage does not decrease.

**Comment by jung-kurt** [comment]
All good points. I like the condition for merging.

**Comment by stanim** [comment]
Mostly people are willing to write tests. If not and the contribution is valuable, we could do it ourselves.

**Comment by stanim** [comment]
Maybe it is good to have little section of contributing code in the documentation, mentioning golint, go vet and coverage condition. So it doesn't come as a surprise.

**Comment by jung-kurt** [comment]
Good idea. I'll add that.
