### ISSUE TITLE
incorrect UTF-8 Rendering ("tofu")

### ISSUE THREAD

**Issue by ajstarks** [jung-kurt/gofpdf#250]
Using this program:
```
package main

import (
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"

	"github.com/jung-kurt/gofpdf"
)

func main() {

	fontdir := os.Getenv("DECKFONTS")
	if len(fontdir) == 0 {
		fmt.Fprintf(os.Stderr, "cannot set the font directory\n")
		os.Exit(1)
	}
	fromFile, err := ioutil.ReadFile("hello.txt")
	if err != nil {
		fmt.Fprintf(os.Stderr, "%v\n", err)
		os.Exit(2)
	}
	pdf := gofpdf.New("P", "pt", "Letter", fontdir)
	pdf.AddPage()
	pdf.AddUTF8Font("deja", "", filepath.Join(fontdir, "DejaVuSansCondensed.ttf"))
	pdf.SetFont("deja", "", 72)
	pdf.Text(100, 300, "Hello, 世界")
	pdf.Text(100, 400, string(fromFile))
	err = pdf.OutputFileAndClose("utf.pdf")
	if err != nil {
		fmt.Fprintf(os.Stderr, "%v\n", err)
		os.Exit(3)
	}
	os.Exit(0)
}
```
The generated PDF file shows "tofu" (empty rectangle) 
when run with this command
``` $ DECKFONTS=$GOPATH/src/github.com/jung-kurt/gofpdf/font go run utftest.go```

I've also attached a screenshot showing the setup and rendering in mupdf and Chrome.

The contents of "hello.txt" is:
```Hello, 世界```

![Screenshot from 2019-05-06 19-54-14](https://user-images.githubusercontent.com/169692/57262498-4df7a480-703a-11e9-95f9-f46295239a98.png)

**Comment by ajstarks** [comment]
Attached is the generated PDF
[utf.pdf](https://github.com/jung-kurt/gofpdf/files/3150266/utf.pdf)

**Comment by jung-kurt** [comment]
I'm not sure about the "tofu" problem. When I call `pdf.Text()` with that string literal it renders correctly, so you may want to hex dump the contents of hello.txt file after it is read to see what is going on.

The Deja Vu fonts do not include CJK code points, so that is the reason the "世界" string does not render. The following works, but the font doesn't seem to support ASCII characters. I am not sure how the font was installed on my system (Ubuntu 18.04).

```go
package main

import (
  "fmt"
  "github.com/jung-kurt/gofpdf"
  "os"
)

func main() {
  pdf := gofpdf.New("P", "pt", "Letter", "")
  pdf.AddPage()
  pdf.AddUTF8Font("deja", "", "/usr/share/fonts/truetype/droid/DroidSansFallbackFull.ttf")
  pdf.SetFont("deja", "", 18)
  pdf.Text(100, 300, "世界")
  err := pdf.OutputFileAndClose("utf.pdf")
  if err != nil {
    fmt.Fprintf(os.Stderr, "%v\n", err)
    os.Exit(3)
  }
  os.Exit(0)
}
```

I think we'll need to include an explanation of this in the README.

**Comment by ajstarks** [comment]
The same happens with the Noto font (no tofu), which is specifically designed to have those code points.
See: https://www.google.com/get/noto/

**Comment by jung-kurt** [comment]
> The same happens with the Noto (no tofu), font which is specifically designed to have those code points.

I downloaded [Noto-SC](https://fonts.google.com/?query=noto&selection.family=Noto+Sans+SC) (世界 shows up properly in the preview) but was unable to convert the OTF files to TTF using [FontForge](https://fontforge.github.io). Were you able to get a TTF directly?

``` shell
$ od -x hello.txt
0000000 6548 6c6c 2c6f e420 96b8 95e7 008c
```
This is a valid utf-8 string according to this [utf-8 tool](http://www.ltg.ed.ac.uk/~richard/utf-8.cgi), so I think it doesn't render for the same reason 世界 doesn't.

**Comment by ajstarks** [comment]
you can get the Noto TTF: here https://www.fontsquirrel.com/fonts/noto-sans

Another font to try is the Go fonts:
If you just want the TTF files, run

```git clone https://go.googlesource.com/image```
and copy them from the subsequent image/font/gofont/ttfs directory.

**Comment by jung-kurt** [comment]
This font worked for me:

    https://github.com/jsntn/webfonts/blob/master/NotoSansSC-Regular.ttf

Note the "SC" suffix which denote simplified Chinese. It properly rendered the ASCII characters, 世界 and the contents of your hello.txt file.

**Comment by ajstarks** [comment]
Great, I can reproduce.  Does the Go Font work for you?

**Comment by jung-kurt** [comment]
> Does the Go Font work for you?

No. One clue is the size of the files.

```
      140308 ./Go-Regular.ttf
     2171336 ./NotoSansSC-Regular.ttf
```

**Comment by ajstarks** [comment]
ok to close
