### ISSUE TITLE
Arabic language

### ISSUE THREAD

**Issue by tharun-d** [jung-kurt/gofpdf#260]
Does this package support Arabic language. data is showing in correct format in my web application table but when download as pdf the strings of Arabic lanfuage are showing another special characters

**Comment by jung-kurt** [comment]
> Does this package support Arabic language. 

Yes. Arabic is included in the [`AddUTF8Font()`](https://godoc.org/github.com/jung-kurt/gofpdf#example-Fpdf-AddUTF8Font) example. It generates [this PDF](https://github.com/jung-kurt/gofpdf/blob/65c03ae855f64ff46c37f9d58ed572a302bd355d/pdf/reference/Fpdf_AddUTF8Font.pdf).

**Comment by jung-kurt** [comment]
Please reopen if this is still an issue
