### ISSUE TITLE
go get -v' returned a non-zero code: 2

### ISSUE THREAD

**Issue by tharun-d** [jung-kurt/gofpdf#267]
../github.com/jung-kurt/gofpdf/utf8fontfile.go:854:19: undefined: math.Round
../github.com/jung-kurt/gofpdf/utf8fontfile.go:872:19: undefined: math.Round

I am getting error while running docker build where docker file has go get -v

**Comment by jung-kurt** [comment]
Have you reached any resolution on this? I am perplexed as to why a standard library function would not be defined.

**Comment by tharun-d** [comment]
oops sorry i defined as FROM golang:1.9.0 AS builder in my docker file this is issue. round is from 1.10 version
