### ISSUE TITLE
Implement RoundedRect

### ISSUE THREAD

**Issue by zaddok** [jung-kurt/gofpdf#272]
A few people have noted needing `RoundedRect`, perhaps its time we include one? 

https://github.com/jung-kurt/gofpdf/issues/126

**Comment by jung-kurt** [comment]
This would be suitable for a first-time contributor. Here's a PHP script on which it could be based:

[Rounded rectangle](http://www.fpdf.org/en/script/script35.php)

**Comment by BeeHam** [comment]
I would like to tackle this, please.
/assign

**Comment by jung-kurt** [comment]
Thanks, @BeeHam
