### ISSUE TITLE
Link the documentation at the top / repo URL

### ISSUE THREAD

**Issue by Moter8** [jung-kurt/gofpdf#3]
http://godoc.org/github.com/jung-kurt/gofpdf should be the website for this project imo. It seems there is no documentation until you see the readme.

**Comment by jung-kurt** [comment]
I'm new to GitHub and am not sure how I would do this. Any examples?

**Comment by Moter8** [comment]
See this screenshot:

![1](https://i.imgur.com/eUIZJj3.png)

You can just go to https://github.com/jung-kurt/gofpdf/ and add the godoc link there :)

**Comment by jung-kurt** [comment]
Got it -- thanks!
