### ISSUE TITLE
Can't "go get": `malformed module path "gofpdf"`

### ISSUE THREAD

**Issue by koinu** [jung-kurt/gofpdf#300]
➜  projects mkdir foo
	➜  projects cd foo
	➜  foo go mod init foo
	go: creating new go.mod: module foo
	➜  foo go get github.com/jung-kurt/gofpdf

	go get: github.com/jung-kurt/gofpdf@v1.12.0 requires
		gofpdf@v0.0.0-00010101000000-000000000000: malformed module path "gofpdf": missing dot in first path element
	➜  foo go version
	go version go1.13 darwin/amd64

**Comment by cwimberger** [comment]
Same issue here, @koinu do you have a workaround?

**Comment by jung-kurt** [comment]
Try
```
go get github.com/jung-kurt/gofpdf@v1.12.1
```
I'm still trying to track down the root issue of this problem. I think it has to do with a circular dependency in contrib/gofpdi.

**Comment by cwimberger** [comment]
It works now, thanks!
