### ISSUE TITLE
Setting border color for cells

### ISSUE THREAD

**Issue by sredxny** [jung-kurt/gofpdf#305]
Hi, is possible to set a color to the border of the cells without filling the cell by itself?

**Comment by jung-kurt** [comment]
Use [`SetDrawColor()`](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.SetDrawColor) to set the border color and false for the fill flag in [`CellFormat()`](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.CellFormat).

```go
package main

import (
  "fmt"

  "github.com/jung-kurt/gofpdf/v2"
)

func main() {
  pdf := gofpdf.New("L", "mm", "A4", "")
  pdf.SetFont("Helvetica", "", 18)
  pdf.AddPage()
  pdf.SetDrawColor(0xff, 0x33, 0x44)
  pdf.CellFormat(50, 30, "Hello, world", "1", 0, "CM", false, 0, "")
  err := pdf.OutputFileAndClose("cell.pdf")
  if err != nil {
    fmt.Print("%s\n", err)
  }
}
```

**Comment by sredxny** [comment]
@jung-kurt  thank you so much. It works!
