### ISSUE TITLE
How can I use arial serif?

### ISSUE THREAD

**Issue by sredxny** [jung-kurt/gofpdf#306]
I understand that the package by default uses arial sans serif, even if I load an external TTF how can I start to use arial serif?

**Comment by jung-kurt** [comment]
Use [`SetFont()`](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.SetFont). For example,
```go
pdf.SetFont("Arial", "B", 16)
```
for 16 pt Arial bold (this is sans serif), or
```go
pdf.SetFont("Times", "", 14)
```
for 14 pt Times New Roman (standard serif font).

**Comment by sredxny** [comment]
@jung-kurt hello, thanks for answer. My mistake, I mean, how to use arial serif, not arial san serif?
As am needing to use serif, but I see that its only available for Times

**Comment by jung-kurt** [comment]
I am not aware of any arial serif font and it definitely is not part of the default base fonts included with PDF readers. If you can find such a font, you will need to add it with [`AddUTF8Font()`](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.AddUTF8Font).
