### ISSUE TITLE
gofpdf.New does not support custom sizes anymore

### ISSUE THREAD

**Issue by steamonimo** [jung-kurt/gofpdf#308]
We use gofpdf to create business cards. With the new current version the following command is now broken and reports "unknown page size 59x89". With the previous release this created a smaller pdf page as expected:

hpdf := gofpdf.New("L", "mm", "59x89", "")

**Comment by jung-kurt** [comment]
I am surprised that the "59x89" notation worked in a previous version; the [page size routine](https://github.com/jung-kurt/gofpdf/blame/648efaf66fc0b2c166ecb8b51fe68bcb0395c840/fpdf.go#L3425-L3442) hasn't changed in six years. In any event, you can create custom sizes using `gofpdf.NewCustom()`; see the [PageSize example](https://godoc.org/github.com/jung-kurt/gofpdf#example-Fpdf-PageSize).

**Comment by steamonimo** [comment]
Somehow your old API handled my abuse. But with NewCustom the behaviour is now as expected. Thanks for pointing me to NewCustom. I will close the issue...
