### ISSUE TITLE
godoc of deprecated repository (code.google.com/p/gofpdf)

### ISSUE THREAD

**Issue by stanim** [jung-kurt/gofpdf#31]
http://godoc.org/code.google.com/p/gofpdf is still referenced by the internet. It would be good if it could point to the github repository.

**Comment by jung-kurt** [comment]
Do you know how to make that happen?

**Comment by jung-kurt** [comment]
It may have been as easy as clicking the refresh button at the bottom of the godoc.org page.

**Comment by stanim** [comment]
Now it gives an error. Some more info would be better.

Do you still have access to the repository? Maybe you can change the docstring of the package by displaying a deprecated warning.

godoc has a redirect mechanism, but no idea if there is a central registry:
https://godoc.org/golang.org/x/tools/godoc/redirect

**Comment by jung-kurt** [comment]
When Google announced that is was shutting down its code service, my first step after transferring to github was to change the documentation to indicate that the project had been moved. A while later, I discovered that code.google.com supported a redirect, so I switched to that method. Unfortunately, godoc.org didn't know what to do with either of those approaches.

**Comment by stanim** [comment]
How does the redirect work? Is the code.google.com repo still go gettable?

**Comment by jung-kurt** [comment]
It must be an HTTP redirect. I cannot access the original https://code.google.com/p/gofpdf or any of its subdirectories anymore.

**Comment by jung-kurt** [comment]
The repo is no longer go gettable:

`package code.google.com/p/gofpdf: unable to detect version control system for code.google.com/ path`

**Comment by jung-kurt** [comment]
The old gofpdf repository at code.google.com no longer shows up in the godoc.org index, and a search for it at that site results in the same "not found" error that a search for any other non-existent site would result in. Since a redirect is in place, anyone visiting code.google.com/p/gofpdf will be redirected to the new github site. I think this is the best we can manage.

**Comment by stanim** [comment]
I agree.
