### ISSUE TITLE
why remove ImageOptionsReader() ?

### ISSUE THREAD

**Issue by Mitu217** [jung-kurt/gofpdf#322]
`ImageOptionsReader` is deleted by https://github.com/jung-kurt/gofpdf/commit/d17d13df9df41d4505501e831ff0ada5b2222ff8 immediately after being merged in https://github.com/jung-kurt/gofpdf/pull/281

I think that we want the ability to insert images retrieved as binary.

Please tell me why it was deleted?

**Comment by jung-kurt** [comment]
> I think that we want the ability to insert images retrieved as binary.

This can be done; see [this example](https://github.com/jung-kurt/gofpdf/blob/9b6b7f4e784dd67fac27ae8fd4aea38136afa1c5/fpdf_test.go#L861-L889).

> Please tell me why it was deleted?

Image attributes were cached improperly.

**Comment by Mitu217** [comment]
@jung-kurt 
thank you immediately answer! 

Sorry, I overlooked the sample. this issue will be closed 🙏
