### ISSUE TITLE
How to support Chinese, Japanese, Korean and other languages at the same time?

### ISSUE THREAD

**Issue by GiveTimeToLife** [jung-kurt/gofpdf#323]
As title,Hope to get a solution, thank you

**Comment by jung-kurt** [comment]
If you cannot find a TrueType font that contains all of the glyphs you need, you will have to load them separately.
```go
pdf.AddUTF8Font("Chinese", "", "/path/to/chinese_font.ttf")
pdf.AddUTF8Font("Japanese", "", "/path/to/japanese_font.ttf")
pdf.AddUTF8Font("Korean", "", "/path/to/korean_font.ttf")
pdf.SetFont("Chinese", "", 12)
pdf.Write(16, "你好 ")
pdf.SetFont("Japanese", "", 12)
pdf.Write(16, "こんにちは ")
pdf.SetFont("Korean", "", 12)
pdf.Write(16, "여보세요 ")
```

**Comment by GiveTimeToLife** [comment]
Thank you for your reply！ Let me try

**Comment by GiveTimeToLife** [comment]
unfortunately, i can ' t find a font that has all the truetypes i need, and a single load doesn ' t fit my needs。pdf.Write(16, "샤오케您好シャオ・ケ")

**Comment by jung-kurt** [comment]
One manually intensive, fragile solution would be to write a script that identifies each UTF-8 code point that you need. Then you could use some font tool to generate your own custom font. I am not familiar with any tools that can do this, but I imagine they are out there.

**Comment by GiveTimeToLife** [comment]
Yes, I can use multiple language TTF files to generate the font files I need. Thank you again for
