### ISSUE TITLE
Charset issue with UTF-8 characters

### ISSUE THREAD

**Issue by Fank** [jung-kurt/gofpdf#326]
I tried following
```go
	// Logo
	pdf.SetFont("Arial", "B", 21)
	pdf.SetXY(2, 2)
	pdf.Cell(40, 10, "KUEGNE+NAGEL")

	// Consignee
	pdf.SetXY(2, 10)
	pdf.SetFont("Arial", "", 8)
	pdf.Cell(10, 10, "Consignee")

	pdf.SetXY(2, 14)
	pdf.SetFont("Arial", "", 10)
	pdf.Cell(10, 10, "Testemfänger")

	pdf.SetXY(2, 18)
	pdf.SetFont("Arial", "", 10)
	pdf.Cell(10, 10, "Testempfänger Straße 1")

	pdf.SetXY(2, 24)
	pdf.SetFont("Arial", "B", 18)
	pdf.Cell(10, 10, "DE 94315")

	pdf.SetXY(2, 30)
	pdf.SetFont("Arial", "", 10)
	pdf.Cell(10, 10, "Straubing")
```

And this is the result
![image](https://user-images.githubusercontent.com/1900106/67089519-1a53a580-f1a8-11e9-8273-88f5b2f46bd2.png)

**Comment by Fank** [comment]
Ok, but why doesn't it support utf-8 by default?

This is the first golang library where i had encoding issues by default.

**Comment by jung-kurt** [comment]
> Ok, but why doesn't it support utf-8 by default?

This package was ported from [FPDF](http://www.fpdf.org/) which itself does not support UTF-8. UTF-8 support in gofpdf was added earlier this year. Additional work will be needed to apply this support to the reader-embedded fonts. Use [gopdf](https://github.com/signintech/gopdf) if you don't want to bother with code pages.

**Comment by Fank** [comment]
Thanks for the info and help, problem solved.
