### ISSUE TITLE
bottom margin for custom size pdf

### ISSUE THREAD

**Issue by schooltech** [jung-kurt/gofpdf#327]
I created a 10cm*7.5cm pdf document, and set the margin to 0.5cm. The result is as shown in the figure, but the margins below are very large. If the pdf document is reduced in height, for example, it is changed to 7.0cm. The document becomes like this. How to solve? Thank you.

![pdf1](https://user-images.githubusercontent.com/16329726/67143246-10ab6a00-f29c-11e9-865c-05395d941100.png)
![pdf3](https://user-images.githubusercontent.com/16329726/67143250-1903a500-f29c-11e9-9911-e6a9afba011f.png)

**Comment by jung-kurt** [comment]
You may want to disable automatic page breaks; see [`SetAutoPageBreak()`](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.SetAutoPageBreak). By default, automatic page breaks are enabled and the bottom margin is set to 2 cm, regardless of the custom page size.

Alternatively, you can set the page break margin with a call to the same method, but I think in the case of tables it makes more sense to disable automatic page breaks.

**Comment by schooltech** [comment]
That's great, Thank you
