### ISSUE TITLE
Render PDF

### ISSUE THREAD

**Issue by oknoorap** [jung-kurt/gofpdf#36]
Can I render PDF on server (render stream output) not write to disk, and not forced to download?

**Comment by jung-kurt** [comment]
After building up a PDF document with various methods such as `AddPage()` and `Cell()`, you obtain the finished PDF by calling `Output()` or `OutputAndClose()` or `OutputFileAndClose()`. The first two of these methods use an `io.Writer` so you are not required to ever generate a file. As long as you have an instance that implements `Write(p []byte) (n int, err error)` you can use it to capture the PDF that you have generated.

**Comment by oknoorap** [comment]
okay thanks.
