### ISSUE TITLE
is .otf format supported?

### ISSUE THREAD

**Issue by badoet** [jung-kurt/gofpdf#38]
tried to run makefont on the otf file
it says 'fonts based on PostScript outlines are not supported'

**Comment by jung-kurt** [comment]
Evidently, according to this [article](https://www.microsoft.com/typography/otspec/otff.htm), OpenType fonts can contain TrueType outlines or PostScript outlines. gofpdf unfortunately supports only the TrueType variety. I'll clarify this in the documentation.

It may be possible for you to convert your OTF file to a TTF file using one of the various online font conversion sites.
