### ISSUE TITLE
inlined multiple MultiCell

### ISSUE THREAD

**Issue by badoet** [jung-kurt/gofpdf#39]
how to draw MultiCell side by side?
when i set width as 60 for both MultiCell, the second MultiCell is drawn below the first.
help?

**Comment by jung-kurt** [comment]
Make sure the MultiCell widths can fit within the margins of your page. See `ExampleFpdf_SetLeftMargin()` in fpdf_test.go. (This example generates Fpdf_SetLeftMargin_multicolumn.pdf in the pdf directory.)

**Comment by badoet** [comment]
hey, thx for replying so fast.
i guess i need to clarify a little
i need to render the column on a height smaller than the page height.
basically i need it to behave like CellFormat with `ln` set to 0, the next CellFormat will be inlined
the multiCell mutli column format seems to just set the page to be 3 column, and there doesnt seems to be a way to limit the maximum height of the MultiCell to be shorter than the page height

**Comment by jung-kurt** [comment]
Here's how someone solved your problem using the original FPDF: [fpdf-height-of-a-multicell-element](http://stackoverflow.com/questions/18356118/fpdf-height-of-a-multicell-element)

**Comment by badoet** [comment]
awesome. thx!
