### ISSUE TITLE
Example code outputs only half of the image

### ISSUE THREAD

**Issue by Moter8** [jung-kurt/gofpdf#4]
The images themselves render as expected in `nautilus` and `chrome`, just not in the exported pdf's.

`go version go1.4.1 linux/amd64`

![0](https://i.imgur.com/2KeliJE.png)
![1](https://i.imgur.com/H7IMZ3r.png)

**Comment by jung-kurt** [comment]
Good catch. I have no idea what could be causing this. I don't have a 64 bit Linux to test this with, but I'll try to set one up. 

When you say the images render as expected in nautilus and chrome, do you mean that tutorial08.pdf and tutorial18.pdf look fine with those applications but not in others?

**Comment by Moter8** [comment]
I meant with "they render as expected" that the images themselves aren't faulty.

![0](https://i.imgur.com/MBGC9P3.png)

**Comment by Moter8** [comment]
@changetip @jung-kurt Thanks for looking into it, 3$

**Comment by changetip** [comment]
Hi @jung-kurt, @Moter8 sent you a Bitcoin tip worth 13,263 bits ($3.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/731989)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by jung-kurt** [comment]
Wow -- a tip! Thanks.

Can you take a look at tutorial02.pdf and the second page of tutorial06.pdf? Each of those documents has a copy of logo.png (one of the two offending images) as well. What's odd about this is that other PNGs render successfully.

What happens if you replace, say, "logo-gray.png" on line 987 of fpdf_test.go with "logo.png"? Maybe you can try modifying the order to see if it's the order or the image that results in clipping.

Do you have alternate PDF viewers you can check the documents in?

**Comment by Moter8** [comment]
Well that is embarrassing. Turns out it renders as expected using mupdf/Ocular. Sorry :P

**Comment by Moter8** [comment]
I'm currently programming for the first time in go and using your library. So far it's been nice, just need to figure out how these cells works etc :)

**Comment by jung-kurt** [comment]
> Turns out it renders as expected using mupdf/Ocular.

Hmm...what viewer caused the problem?

> I'm currently programming for the first time in go and using your library. 

You'll enjoy Go and its first rate tooling and standard library. Have fun!

> So far it's been nice, just need to figure out how these cells works etc :)

Cells in gofpdf? I should probably document them better, perhaps with some diagrams.

**Comment by Moter8** [comment]
Chromium's pdf plugin caused that.

Yeah, I meant Cells in gofpdf, I noticed some weird behaviour, I'll try to reproduce it.
Diagrams would certainly help :dart:
