### ISSUE TITLE
cant seems to do underline with html.write

### ISSUE THREAD

**Issue by badoet** [jung-kurt/gofpdf#40]
tried to do html.Write(`<u>underline this</u>`)
and it doesnt underline the word. 
is underline not supported?
thx

**Comment by jung-kurt** [comment]
Underlining is supported and demonstrated in the `ExampleFpdf_HTMLBasicNew()` example in fpdf_test.go. After running `go test`, do you see underlining in pdf/Fpdf_HTMLBasicNew.pdf?

**Comment by badoet** [comment]
yea, just realized that the underline is very thin and close to the words
