### ISSUE TITLE
Concurrent page rendering?

### ISSUE THREAD

**Issue by ajstarks** [jung-kurt/gofpdf#41]
In order to speed up the rendering in pdfdeck (https://github.com/ajstarks/deck/tree/master/cmd/pdfdeck) I'd like to experiment with concurrent rendering of slides. (see Line 312 for the function that does this)

Questions: 
1) are the rendering functions safe for concurrent use?
2) Suggested approaches to concurrent page rendering.

**Comment by marcusatbang** [comment]
You could do this by creating templates that *aren't* attached to an existing document, then combining them at the end.

```
template := gofpdf.CreateTemplate(corner, size, "mm", "", func (tlp *gofpdf.Tpl) {
    // write page content
})

// in a separate thread, once all
pdf := gofpdf.New(" P", "mm", " A4", "")
for _, template := range something {
    pdf.AddPage()
    pdf.UseTemplate(template)
}
```

Fan-in threading is left as an exercise to the reader. And I strongly suggest that you run lots of tests to establish whether it really does provide any performance benefit or not.

**Comment by jung-kurt** [comment]
Thanks, @marcusatbang, for your solution and remarks.

@ajstarks, there is currently no provision to make any of the methods in gofpdf safe for concurrent use.
