### ISSUE TITLE
Text show over flow width

### ISSUE THREAD

**Issue by veenutanwar** [jung-kurt/gofpdf#47]
Dear
when i use CellFormat and give width then why text overflow the width ?

**Comment by jung-kurt** [comment]
`CellFormat()` handles text that fit within the bounding rectangle. If you need to clip the text at the rectangle, use the `ClipText()` method. See [this code](https://godoc.org/github.com/jung-kurt/gofpdf#example-Fpdf-ClipText) for an example of its use.
