### ISSUE TITLE
html basic without any tag

### ISSUE THREAD

**Issue by ghigt** [jung-kurt/gofpdf#5]
Is it normal that nothing is printed without any tag when I'm calling the html method?

```go
pdf := gofpdf.New("P", "mm", "A4", "")
pdf.AddPage()
pdf.SetFont("Times", "", 13)
_, lineHt := pdf.GetFontSize()
html := pdf.HTMLBasicNew()
html.Write(lineHt, "<>first</>")
html.Write(lineHt, "second")
if e := pdf.OutputFileAndClose("./p.pdf"); e != nil {
	log.Fatal(e)
}
```
It results in printing `first` but not `second`.

**Comment by jung-kurt** [comment]
Good catch. The tokenizer was erroneously expecting at least one tag in the text passed to Write(). It should work now.

**Comment by ghigt** [comment]
:+1: thanks
