### ISSUE TITLE
Multicell same height on the row

### ISSUE THREAD

**Issue by gpopovic** [jung-kurt/gofpdf#51]
I'm having problems with building a table row.

It can happend that a first column in a row has height of 40, and the second column in the same row gets larger because text is too large.

Because of that i get unaligned borders..
Is it possible to somehow define row border?

**Comment by jung-kurt** [comment]
You may want to use SplitLines() to calculate in advance the maximum height of each column in a row. You can then apply the maximum height in the row to each column.

**Comment by gpopovic** [comment]
Thanks, managed to do it
