### ISSUE TITLE
How to use czech language

### ISSUE THREAD

**Issue by hypertornado** [jung-kurt/gofpdf#54]
I am trying to use gofpdf with czech language. First I exported "Arial.json" and "Arial.z" with:

```
./makefont --embed --enc=../font/cp1250.map --dst=/somepath /Library/Fonts/Arial.ttf
```

Then i use code to generate pdf:
```
pdf := gofpdf.New("L", "mm", "A4", "")
pdf.AddPage()
pdf.AddFont("arial", "", "/somepath/Arial.json")


pdf.SetFont("arial", "", 16)
pdf.Cell(10, 10, "Dárkový poukaz v hodnotě")
```

But instead of text "Dárkový poukaz v hodnotě", I got "DĂĄrkovĂ˝ poukaz v hodnotÄ". I don't know if czech language is supported. What should I do to have czech text displayed properly?

**Comment by jung-kurt** [comment]
I don't believe code page 1250 is what you want. Does [code page 852](https://en.wikipedia.org/wiki/Code_page_852) include the glyphs you need?

**Comment by jung-kurt** [comment]
On second reading, I see that your example does not UnicodeTranslatorFromDescriptor() to handle the non-ASCII characters. You are probably fine with your code page 1250 font. See ExampleFpdf_CellFormat_4() for an example.

**Comment by hypertornado** [comment]
Thanks, that was the problem. I created pull request #55 so that cp1250 is easier to use.
