### ISSUE TITLE
Small Caps

### ISSUE THREAD

**Issue by scisci** [jung-kurt/gofpdf#56]
I have a font that supports small caps but can't figure out how to use those small caps in the pdf. I tried hacking in and modifying the .json Flags property to include Small Caps flag (1 << 18) but no effect. Any Idea?

**Comment by jung-kurt** [comment]
I was not familiar with that smalls caps descriptor flag, and am not quite sure how OpenType implements small caps. If the font simply replaced lower case letters with small caps, one could use [AddFont()](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.AddFont) as in [this example](https://godoc.org/github.com/jung-kurt/gofpdf#example-Fpdf-AddFont). If the font supports [Unicode small caps](https://en.wikipedia.org/wiki/Small_caps#Unicode) I think a code page file would need to be made for it. I have seen an FPDF add-on solution that generates its own small caps and provides a new method for [Cell()](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.Cell),  but that would not take advantage of native small caps.

**Comment by scisci** [comment]
I was able to create a custom font that froze Small Caps into the lowercase letters using this tool:
https://github.com/twardoch/fonttools-utils/tree/master/pyftfeatfreeze

**Comment by jung-kurt** [comment]
Excellent tool -- I am glad to learn of it.

If you care to write up a short summary I will put it into gofdpf's documentation.
