### ISSUE TITLE
How to display chinese characters ?

### ISSUE THREAD

**Issue by toplinuxsir** [jung-kurt/gofpdf#59]
How to display chinese characters ?
Should I use cp1252.map ?
Thanks !

**Comment by jung-kurt** [comment]
Unfortunately, gofpdf doesn't currently support Chinese, Korean and Japanese fonts since it is restricted to using code pages that have a maximum of 256 characters. 

Code page 1252 contains only western characters so it won't help here.

You may want to take a look at [gopdf](https://github.com/signintech/gopdf). It now supports Unicode font subsetting.

**Comment by toplinuxsir** [comment]
I think gofpdf is great , any plan to support Asian characters ?

**Comment by jung-kurt** [comment]
I definitely want to Asian characters. Any help in that regard will be greatly appreciated!

**Comment by thinkingdyw** [comment]
when to support Chinese？

**Comment by jung-kurt** [comment]
I recently exchanged emails with a company that planned to implement full Unicode support for gofdpf, but I am not sure if it will contribute its changes to the project or when that task will be complete.

**Comment by marcusatbang** [comment]
That would be impressive, and useful. PDF has a shaky and complicated relationship with Unicode, so it's not a simple question. I'd be interested in hearing how they plan to address eg font subsetting?

**Comment by jung-kurt** [comment]
Does font subsetting imply that a stripped-down font file is always embedded in the PDF?

**Comment by marcusatbang** [comment]
If it's a non-standard font, yes. And languages other than English are likely to use non-standard fonts.

One of the hurdles facing my (stalled) attempt to port FPDI was the need to merge font subsets, and deal with code pages. I never really had an answer to that, that wasn't huge amounts of work.

**Comment by jung-kurt** [comment]
Thanks, @marcusatbang -- I hope we can tackle this someday.
