### ISSUE TITLE
Arial or Helvetica

### ISSUE THREAD

**Issue by jamesajones** [jung-kurt/gofpdf#60]
You mention in the docs that Helvetica(aka arial) is this actually true? Have read that Helvetica is a likely ancestor of arial is that what you mean? Have a need to use arial as a requirement.

**Comment by jung-kurt** [comment]
The author of [fpdf](http://fpdf.org/) considered Arial and Helvetica to be close enough that if Arial was specified, it was replaced with the core font Helvetica.

    if familyStr == "arial" {
        familyStr = "helvetica"
    }

If you need Arial, you'll need to explicitly load it. See `ExampleFpdf_AddFont()` in fpdf_test.go for an example. You will need to use a name other than "Arial" to prevent the package from substituting it.

**Comment by jamesajones** [comment]
Thanks for clearing that up
