### ISSUE TITLE
Changing Fonts in mid-line

### ISSUE THREAD

**Issue by jamesajones** [jung-kurt/gofpdf#61]
Am currently handling this this way:
// Current Weight
pdf.SetFont("Helvetica", "B", 11)
pdf.CellFormat(1.8, 0, "4.  Current Weight: ", "", 0, "L", false, 0, "")
pdf.SetFont("Helvetica", "", 11)
pdf.CellFormat(PDF_INTERNAL_WIDTH/4, 0, ""+CurrentWeight, "", 1, "LM", false, 0, "")
pdf.Ln(.2)
Is there some thing I am missing that would reduce the amount of code?
Thanks,
Jim

**Comment by jung-kurt** [comment]
*Very* basic HTML may help you here if you don't require alignment other than left. See `ExampleFpdf_HTMLBasicNew()` for an example.
