### ISSUE TITLE
cyrillic text in pdf

### ISSUE THREAD

**Issue by shahmuratov** [jung-kurt/gofpdf#64]
Hello! I need to create cyrillic text in pdf but example found in docs not working. Here is code
```
package main

import (
    "github.com/jung-kurt/gofpdf"
    "fmt"
    "os"
)

func main() {
    pwd, err := os.Getwd()
    if err != nil {
        fmt.Println(err)
        os.Exit(1)
    }
    pdf := gofpdf.New("P", "mm", "A4", "")
    pdf.AddFont("Helvetica", "", pwd + "/font/helvetica_1251.json")
    pdf.AddPage()
    pdf.SetFont("Helvetica", "", 16)
    tr := pdf.UnicodeTranslatorFromDescriptor("cp1251")
    pdf.Cell(15, 50, tr("русский текст"))
    pdf.OutputFileAndClose("test.pdf")
}
```
I receive only dots.

**Comment by jung-kurt** [comment]
Instead of
```
pdf := gofpdf.New("P", "mm", "A4", "")
pdf.AddFont("Helvetica", "", pwd + "/font/helvetica_1251.json")
```
try
```
pdf := gofpdf.New("P", "mm", "A4", pwd + "/font")
pdf.AddFont("Helvetica", "", "helvetica_1251.json")
```

**Comment by shahmuratov** [comment]
I've tried but this doesn't helped. This only reproduces on Windows 10. When I try it on Mac OS X everything works fine even with original code. On Windows I get only dots. Generated files differ yet fonts used to create them the same. I've attached both files
[test_mac.pdf](https://github.com/jung-kurt/gofpdf/files/131406/test_mac.pdf)
[test_win.pdf](https://github.com/jung-kurt/gofpdf/files/131407/test_win.pdf)

**Comment by jung-kurt** [comment]
Thanks for the example files. Could you please run the same test on both platforms with compression turned off (see [SetCompression](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.SetCompression)) and resubmit the output?

**Comment by shahmuratov** [comment]
It worked on Windows 10 with SetCompression. Attaching result file. Thank you very much!
[test_win.pdf](https://github.com/jung-kurt/gofpdf/files/133956/test_win.pdf)

**Comment by shahmuratov** [comment]
Well generally it now works even without SetCompression. I can't understand what changed. Here is my final code:
package main

import (
    "github.com/jung-kurt/gofpdf"
    "fmt"
    "os"
)

func main() {
    pwd, err := os.Getwd()
    if err != nil {
        fmt.Println(err)
        os.Exit(1)
    }
    pdf := gofpdf.New("P", "mm", "A4", pwd + "/font/")
    pdf.AddFont("Helvetica", "", "helvetica_1251.json")
    pdf.AddPage()
    pdf.SetFont("Helvetica", "", 16)
    tr := pdf.UnicodeTranslatorFromDescriptor("cp1251")
    pdf.Cell(15, 50, tr("русский текст"))
    pdf.OutputFileAndClose("test.pdf")
}
I think we can close this bug

**Comment by jung-kurt** [comment]
Hmmm. If you ever identify what the problem was, please let me know so I can update the documentation.
