### ISSUE TITLE
Support for variable image dpi needs work

### ISSUE THREAD

**Issue by kentquirk** [jung-kurt/gofpdf#66]
Trying to right-justify an image -- even if you know its dpi -- is a bit of work. The imginfo.Extent() and related functions assume that the image is 72 dpi.

Here's what I had to do:

```go
	imginfo := pdf.RegisterImage(imgname, "")
	imgdpi := float64(288)
	widthInPixels := pdf.UnitToPointConvert(imginfo.Width())
	w := widthInPixels * pdf.PointToUnitConvert(72/imgdpi)
	pgw, _ := pdf.GetPageSize()
	lm, _, rm, _ := pdf.GetMargins()
	imgpos := pgw - lm - rm - w
	pdf.Image(imgname, imgpos, 0, -imgdpi, -imgdpi, true, "", 0, "")
```

The easiest fix I can see (since the Go image routines don't provide dpi info) would be to provide an imginfo.DpiExtent function that takes dpi as a parameter. 

A better fix would be to allow setting DPI on an image and having it taken into account. Perhaps imginfo could grow a dpi field, it could be set to 72 by default, but if you override it, it would get taken into account.

I'd be willing to submit a PR with a fix, but I'd like to know what sort of fix you'd approve before I do it, please.

**Comment by jung-kurt** [comment]
@kentquirk Thanks for your offer to help with this.

> A better fix would be to allow setting DPI on an image and having it taken into account. Perhaps imginfo could grow a dpi field, it could be set to 72 by default, but if you override it, it would get taken into account.

This definitely is the right approach. A PR will be very welcome.

**Comment by kentquirk** [comment]
Great, thanks. I'm on it.

**Comment by jung-kurt** [comment]
Thanks for your work on this, @kentquirk 

Closing this issue because it is resolved by your [pull request](https://github.com/jung-kurt/gofpdf/pull/68).
