### ISSUE TITLE
Support for non-ASCII text (Á, é, ê, Ç, ã)

### ISSUE THREAD

**Issue by nathyecomp** [jung-kurt/gofpdf#67]
Hi,  I would like to know if it is possible to generate portuguese/spanish pdfs by using your library. I was trying to use a google's font that has these characters (Roboto-Regular.ttf), but it did not work

**Comment by jung-kurt** [comment]
@nathyecomp Spanish and Portuguese should render properly with the default code page 1252. See [ExampleFpdf_CellFormat_4](https://godoc.org/github.com/jung-kurt/gofpdf#example-Fpdf-CellFormat-4) for an example of how to automatically convert your UTF-8 source text to the 8-bit encoding the gofpdf uses internally. If you like, I will extend that example with characters such as Á, é, ê, Ç, ã -- let me know.

**Comment by jung-kurt** [comment]
@nathyecomp I just added a Portuguese example with diacritics [here](https://github.com/jung-kurt/gofpdf/blob/master/fpdf_test.go#L1290-1291).
