### ISSUE TITLE
AddFontFromReader loads definition but not font file

### ISSUE THREAD

**Issue by jskrepnek** [jung-kurt/gofpdf#72]
Hi,

Thanks for this work.

I was looking for a solution to add a custom font without having to load any files.  I thought  AddFontFromReader would do that, but it appears to only load the definition from a reader.  As far as I can tell the library attempts to load the font itself (font.z) from the file system.  As it currently stands, is there a way to supply a custom font in another way?

**Comment by jung-kurt** [comment]
@jskrepnek Take a look at [`ExampleFpdf_SetFontLoader()`](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.SetFontLoader) in fpdf_test.go. It uses the `SetFontLoader()` to load both the .z and .json font files from a generalized io.Reader.

**Comment by jskrepnek** [comment]
Thanks Kurt, worked like a charm.

**Comment by jung-kurt** [comment]
> Thanks Kurt, worked like a charm.

Good!
