### ISSUE TITLE
RFE: TIFF Support

### ISSUE THREAD

**Issue by dtrehas** [jung-kurt/gofpdf#74]
is there any planning to incorporate  TIFF  support (G3, G4 encoding) in your project?

Thank you in advance

**Comment by jung-kurt** [comment]
There are no current plans to support TIFF directly although I would welcome a solution if submitted.

In the mean time, you could execute `convert` (part of the [ImageMagick suite](http://www.imagemagick.org/script/index.php)) to convert TIFF images to one of the three supported formats. See the `min()` function in [ghostscript.go](https://github.com/jung-kurt/gofpdf/blob/master/contrib/ghostscript/ghostscript.go) for an example of how to execute external commands from within your application using pipes.
