### ISSUE TITLE
Fix for: Templates doesn't view special characters and font's correctly

### ISSUE THREAD

**Issue by geekpex** [jung-kurt/gofpdf#75]
When using this package I noticed that if you change font in template, the template still uses default font style in output (Atleast when viewed on Acrobat Reader). Also encoding of special characters doesn't work.
I noticed that in output file XObject doesn't have Resource reference to declared Font objects.
_(This is only recommended on PDF standard)_
**Fix:**
On templates.go file (line: 113,  function putTemplates) I just added Font resource declaration (after line 136):

> 		f.out("/Font <<")
> 		{
> 			var keyList []string
> 			var font fontDefType
> 			var key string
> 			for key = range f.fonts {
> 				keyList = append(keyList, key)
> 			}
> 			if f.catalogSort {
> 				sort.Strings(keyList)
> 			}
> 			for _, key = range keyList {
> 				font = f.fonts[key]
> 				f.outf("/F%d %d 0 R", font.I, font.N)
> 			}
> 		}
> 		f.out(">>")

After the "/ProcSet ..." output:

> 		f.out("/Resources ")
> 		f.out("<</ProcSet [/PDF /Text /ImageB /ImageC /ImageI]")

**Comment by jung-kurt** [comment]
Thanks, @geekpex -- good catch and good fix!

**Comment by geekpex** [comment]
Just noticed this fix is not fully working, it only fixes character encoding. Font styles to work, we need to copy fonts map to templates base Fpdf.
On file template_impl.go I added below line to "loadParamsFromFpdf" function (line: 91):

> t.Fpdf.fonts = f.fonts

**Now** you can add new font styles on templates.

**Comment by jung-kurt** [comment]
Got it -- thanks, @geekpex

**Comment by marcusatbang** [comment]
I fear that a full treatment of fonts in templates could be much larger and more complicated. For example, if the base document and the template included two different subsets of the same font.

**Comment by geekpex** [comment]
Yes, that's true. You can't add new external fonts in template with this fix. But atleast, if you add all necessary external font's in base document, you can change font style and family in the template itself. And for me the most important thing was that encoding of special characters works now.

**Comment by marcusatbang** [comment]
Oh, this is definitely a positive step.
