### ISSUE TITLE
I did a simple utf-8 to windows-1232 conversion routine

### ISSUE THREAD

**Issue by gilmarpalega** [jung-kurt/gofpdf#80]
Hello guys,
I wrote a simple package to do this charset translation, to avoid creating extra font maps. Not sure if this will help anyone, in any case, here it is.

https://github.com/gilmarpalega/cp1232

**Comment by jung-kurt** [comment]
Hi @gilmarpalega 

In fact, gofpdf does something like this already -- see [UnicodeTranslator](https://godoc.org/github.com/jung-kurt/gofpdf#UnicodeTranslator) and the [codepage example](https://godoc.org/github.com/jung-kurt/gofpdf#example-Fpdf-CellFormat-Codepage). Your solution is easier to use, but assumes the Windows Latin 1 codepage and is limited to selected runes. The internal solution is more general but requires a code page descriptor file to function.

Thanks for your interest!
