### ISSUE TITLE
color.CMYKModel undefined, breaks build

### ISSUE THREAD

**Issue by core433** [jung-kurt/gofpdf#82]
A few days ago my app started breaking when I run `go get github.com/jung-kurt/gofpdf` with this error:

src/github.com/jung-kurt/gofpdf/fpdf.go:2875: undefined: color.CMYKModel

It looks like this PR made 9 days ago broke things:
https://github.com/jung-kurt/gofpdf/commit/93a9d1608a79dd7957cfe4c4a8270c2b82dca6bc

Has nobody else been seeing this?  Am I missing something to support CMYKModel?  If not, could we please back it out?

**Comment by core433** [comment]
@midiland @jung-kurt

**Comment by jung-kurt** [comment]
@core433 Try issuing the following git command from the gofpdf directory:

    git reset --hard

It may be that `go get` isn't properly updating your repository for some reason.

**Comment by core433** [comment]
Was using Golang 1.4.2, upgrading to 1.6.3 fixed the issue.  Thanks for helping!
