### ISSUE TITLE
Data race

### ISSUE THREAD

**Issue by RubenN** [jung-kurt/gofpdf#84]
Trying to generate QR's in pdf's in a go-routine and once in a while the following occurs:

WARNING: DATA RACE
Read at 0x00c04a9ef620 by goroutine 29:
  github.com/jung-kurt/gofpdf/contrib/barcode.Register()
      d:/projects/go/src/github.com/jung-kurt/gofpdf/contrib/barcode/barcode.go:95 +0x58
  github.com/jung-kurt/gofpdf/contrib/barcode.registerBarcode()
      d:/projects/go/src/github.com/jung-kurt/gofpdf/contrib/barcode/barcode.go:183 +0x57
  github.com/jung-kurt/gofpdf/contrib/barcode.RegisterQR()
      d:/projects/go/src/github.com/jung-kurt/gofpdf/contrib/barcode/barcode.go:161 +0xa5

Any ideas on how to prevent this?

**Comment by jung-kurt** [comment]
@RubenN Is the PDF instance (returned from `New()` or `NewCustom()`) used exclusively in its own goroutine? PDF instances are definitely not shareable among goroutines.

Have you tried running your program with the [race detrector](https://blog.golang.org/race-detector)?

**Comment by jung-kurt** [comment]
I should speak for myself about using the race detector. I just ran it and found three race conditions in the barcode contributed code. I will look into this and report back.

**Comment by RubenN** [comment]
@jung-kurt Yes it is, I'm using the following code:

```
	key := barcode.RegisterQR(pdf, UUIDbase64url, qr.H, qr.Auto)
	barcode.Barcode(pdf, key, 258, 11, 25, 25, false)
```

As a workaround I changed it to use mutexes because of the maps beiing used in the barcode contrib:

```
	mutex.Lock()
	key := barcode.RegisterQR(pdf, UUIDbase64url, qr.H, qr.Auto)
	barcode.Barcode(pdf, key, 258, 11, 25, 25, false)
	mutex.Unlock()
```

I guess it would be best to solve this problem there though.

**Comment by jung-kurt** [comment]
@RubenN Updating [boombuler/barcode](the https://github.com/boombuler/barcode) packages corrected the race problem.

It may be sufficient to run `go get -u github.com/jung-kurt/gofpdf/contrib/barcode` but, if not, you can run
 `go get -u github.com/boombuler/barcode`.

**Comment by RubenN** [comment]
@jung-kurt That doesn't resolve my problem; it has something to do with access to the map in the barcode contrib:

```
// barcodes represents the barcodes that have been registered through this
// package. They will later be used to be scaled and put on the page.
var barcodes map[string]barcode.Barcode
```

Which is exactly why the mutex I put around the RegisterQR works (see previous comment).

**Comment by jung-kurt** [comment]
@RubenN Yes, I see the problem. Would it be sufficient to put a mutex around the code in `Register()`? That's the only place I can see that writes to the map. If that solves the problem, I will update the code. That way, applications will not have to fuss with it.

**Comment by RubenN** [comment]
@jung-kurt I did more reading on this subject and understand that both reading and writing should be protected. Will test first tomorrow and come back with the result.

**Comment by jung-kurt** [comment]
Thanks, @RubenN We really should evaluate whether caching barcodes in that map even makes sense. I doubt too many applications reuse a barcode once it is placed in a PDF. If they do, and if multiple goroutines are the norm, then yes, protecting the reading and writing of the map makes sense.

**Comment by RubenN** [comment]
@jung-kurt I added mutex protection and informed author of contrib. He already made the neccesary adjustments. Please review :-)

**Comment by jung-kurt** [comment]
Thanks, @RubenN .
