### ISSUE TITLE
how to convert fpdf to io.Reader ?

### ISSUE THREAD

**Issue by fuku2014** [jung-kurt/gofpdf#86]
I want get buffer.

**Comment by jung-kurt** [comment]
@fuku2014 A bytes.Buffer implements the io.Writer interface, so you could pass one to [Output()](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.Output) to get a buffer that holds the PDF.

If you need to write directly to the PDF buffer, you can try [RawWriteBuf()](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.RawWriteBuf).

**Comment by fuku2014** [comment]
Thanks!
I can get io.Reader.
```
var result bytes.Buffer
pdf.Output(&result)
reader := bufio.NewReader(&result)
```
