### ISSUE TITLE
Font embedding

### ISSUE THREAD

**Issue by claudiofelber** [jung-kurt/gofpdf#9]
I would like to create a Go binary with embedded font files (.json and .z). I will do this by appending a ZIP file containing all the required files to the Go generated binary. So far so good. In order to be able to use these embedded font files with gofpdf I would like to have it accept readers for **both** .json and .z files. Currently it only supports loading the .json font file from an io.Reader using `AddFontFromReader`. The actual font data (.z) is then loaded using the file system call. This makes `AddFontFromReader` effectively useless.

In order to support font files embedded into the executable (or maybe reading them from a ZIP file) I would propose to add a `SetFontOpener(opener FontOpener)` method to the `Fpdf` struct where `FontOpener` is an interface defined as follows:

```
type FontOpener interface {
    Open(name string) io.Reader, error
}
```

The `Open` method could then be called to get readers for both the .json and .z font files. In order to keep the interface as non-restrictive as possible I defined it to return an io.Reader instead of an io.ReaderCloser. Nevertheless you could close closeable readers in your code using the following fragment:

```
reader, err := f.opener.Open(fontFile)
…

if closer, ok := reader.(io.Closer); ok {
    closer.Close()
}
```

**Comment by jung-kurt** [comment]
Sorry for the delay in this response -- for some reason I wasn't notified by github.

Thanks for the excellent observation and proposal. The fact that font contents have been loaded with `ioutil.ReadFile` somehow escaped me when the `io.Reader` patch was submitted.

I think closing the reader should depend on the `FontOpener` both implementing the `Close` interface as well as some argument to `Open` indicating that the reader should be closed after loading the font. It would be annoying for the caller if the reader happened to implement `Close` but needed to stay open for some reason.

**Comment by jung-kurt** [comment]
Many thanks for a first-rate implementation, and also for the dashed line functionality. Both have been merged in.
