### ISSUE TITLE
How to add image with go-bindata?

### ISSUE THREAD

**Issue by fuku2014** [jung-kurt/gofpdf#92]
I use [go-bindata](https://github.com/jteeuwen/go-bindata) for single binary.
Can gofpdf handle this?

**Comment by jung-kurt** [comment]
Yes, embedded binary data resources are supported. When you make a call like
```
data, err := Asset("img/001.jpg")
```
to retrieve an embedded image or font, you get a byte slice. You can get an io.Reader for the data by using the bytes package: 
```
r := bytes.NewReader(data)
```
You can then use the reader in calls to [AddFontFromReader](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.AddFontFromReader) and [RegisterImageOptionsReader](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.RegisterImageOptionsReader).

**Comment by fuku2014** [comment]
Cool!
I can use this.
Thanks.
