### ISSUE TITLE
Question: Combining pdf's

### ISSUE THREAD

**Issue by willtrking** [jung-kurt/gofpdf#93]
I'd like to combine multiple gofpdf's into a single pdf, is there a way to do this easily, or should they all be written together in 1 (which I'd like to avoid to keep accurate page numbering)? 

Checked the docs, but I don't see anything

Thanks in advance!

**Comment by jung-kurt** [comment]
I think your best bet will be to write the documents together. You can modify the page number that gets displayed in your header or footer function (see the [AddPage example](https://godoc.org/github.com/jung-kurt/gofpdf#example-Fpdf-AddPage). gofpdf needs to keep track of the physical page number for linking and other purposes, but the page number that gets printed is completely up to you. For example, if on a certain page you want to reset the displayed page number to 1, you could store the value returned by [pdf.PageNo()](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.PageNo) and subtract it from pdf.PageNo() + 1 for subsequent pages.

**Comment by willtrking** [comment]
Sounds good, I'll stick with that route then, thanks!
