### ISSUE TITLE
How to rotate the page ?

### ISSUE THREAD

**Issue by huayi** [jung-kurt/gofpdf#94]
I want to rotate the page like this:
![qq 20161128111002 -](https://cloud.githubusercontent.com/assets/6790268/20655225/9cadc312-b55b-11e6-9ce0-ba07626b4f17.png)

rotate to :

![qq 20161128111002](https://cloud.githubusercontent.com/assets/6790268/20655210/5fe2c004-b55b-11e6-9939-1a927253585a.png)

**Comment by jung-kurt** [comment]
Place your text, drawing and image after a call to [TransformBegin()](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.TransformBegin) and [TransformRotate()](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.TransformRotate). Be sure to call [TransformEnd()](https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.TransformEnd) afterward.

For example:

```
package main

import (
        "fmt"
        "github.com/jung-kurt/gofpdf"
)

func main() {
        var err error
        var pdf *gofpdf.Fpdf

        pdf = gofpdf.New("P", "mm", "A4", "") // A4: 210.0 x 297.0
        pdf.AddPage()
        pdf.SetFont("Arial", "B", 32)
        pdf.TransformBegin()
        pdf.TransformRotate(-90, 105, 145)
        pdf.CellFormat(105, 145, "Hello World!", "", 0, "C", false, 0, "")
        pdf.TransformEnd()
        err = pdf.OutputFileAndClose("hello.pdf")
        if err != nil {
                fmt.Println(err)
        }
}
```

**Comment by huayi** [comment]
Thanks a lot !
