### ISSUE TITLE
CellFormat() and MultiCell() behave differently when no wrapping is needed

### ISSUE THREAD

**Issue by rallant92** [jung-kurt/gofpdf#96]
I have noticed that these two lines of code behave differently when a short string is used and no wrapping is needed:
pdf.CellFormat(w[1], 1, path, "1", 0, "L", false, 0, "")
vs
pdf.MultiCell(w[1], 1, path, "1", "L", false)

This draws the middle cell of a 3x3 table, full page width (less 0.75in margins).  MultiCell() results in a different x and y that results in the third cell being positioned on the next line instead of the same line.

Here is the x and y (in inches) after calling CellFormat() vs MultiCell():
x:  6.25 y:  1.75
x:  6.25 y:  2.75
x:  6.25 y:  3.75
vs
x:  0.75 y:  2.75
x:  0.75 y:  4.75
x:  0.75 y:  6.75

My work around is to save and restore+fix x and y around MultiCell (I want it's wrapping ability for long text).
x, y = pdf.GetXY()
pdf.MultiCell(w[1], 1, path, "1", "L", false)
pdf.SetXY(x+w[1], y)

**Comment by jung-kurt** [comment]
Thanks, @rallant92, for the report.

The example for [MultiCell](https://godoc.org/github.com/jung-kurt/gofpdf#example-Fpdf-MultiCell) demonstrates automatic line wrapping. Is it possible for you to combine all the text you will be rendering into one string and submit it in one call to MultiCell? Or are you using different attributes for different parts of the text? If so, it may be that we should add a new variation of MultiCell that uses an argument like CellFormat that dictates what should happen to the current position after a call.

**Comment by rallant92** [comment]
Hello Kurt,

I suspect I did not explain my expected behavior of CellFormat() well
enough.  If, in the test code's improved table of country info, I replace
the the CellFormat call for the capitalStr, which the second column, or
fpdf_test.go:368, with a call to MultiCell(), I'd expect the table to look
the same (the capital strings should draw but are too short to need
wrapping), but the following cells will be at "wrong/changed" positions.
The two calls differ when drawing short strings, but should not.

In my particular case, my cell has file path names, which may be really
short or really long, so sometimes it helps to wrap but often not.
CellFormat does not wrap long strings, so MultiCell seems necessary to have
wrapping functionality.


As a side note, if you're curious how people like me are using gofpdf,  I
also need to draw an image in the first column (thumbnail of the file).  I
didn't see image support in cells, so the code calls CellFormat(""), then
goes back and draws an image over the cell.  I don't know if it's the best
way, but it works!


                    pdf.CellFormat(w[0], 1, "", "1", 0, "C", false, 0, "")

                    // draw the image over cell just drawn
                    x, y := pdf.GetXY()
                    pdf.SetXY(x-2, y)
                    pdf.ImageOptions(path, x-2+2*(1.0-thumbnail_scale)/2,
                        y+1*(1.0-thumbnail_scale)/2, 2*thumbnail_scale,
                        1*thumbnail_scale, false, image_opts, 0, "")
                    pdf.SetXY(x, y)

                    // pdf.CellFormat(w[1], 1, path, "1", 0, "L", false, 0,
"")
                    x, y = pdf.GetXY()
                    pdf.MultiCell(w[1], 1, path, "1", "L", false) //
doesn't change x,y like CellFormat() does, so manually fix
                    pdf.SetXY(x+w[1], y)
                    //fmt.Println("x: ", x, "y: ", y)
                    pdf.CellFormat(w[2], 1, t.Format(dateOutputFormat),
"1", 0, "C", false, 0, "")
                    pdf.Ln(-1)


-Roger

**Comment by jung-kurt** [comment]
Thanks, @rallant92, for the explanation. In fact, the incorrect positioning that results from using MultiCell() in the tables example is exactly what happens with CellFormat() if the `ln` argument is changed from 0 to 1. This argument specifies what should happen to the current position after the method call. A value of 0 leaves the current position at the end of the just-drawn text. A value of 1 places it at the beginning of the next line. The MultiCell() method, which does not have this parameter, always puts the current position at the beginning of the next line. That's why I proposed adding a new variation of MultiCell() that accepts the `ln` argument. (We would not want to break backward compatibility by changing the signature of MultiCell()). However, there could be some line-wrapping complications with successive calls to such a variant so it might not be totally straightforward.

Putting an image in an empty cell created by CellFormat("") is creative! The proper size and border are taken care of by CellFormat(), so it's a good way to preserve the correct appearance of the table.

**Comment by rallant92** [comment]
>The MultiCell() method, which does not have this parameter, always puts
the current position at the beginning of the next line.

Ah, I did not pick up on that.  Since that's the behavior is intended to
match CellFormat wihen ln=1, could you please clarify that in
https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.MultiCell?  Borrowing
from the wording used for both calls, something like:

The current position after MultiCell is the beginning of the next line,
equivalent to calling CellFormat with ln=1.

That one line would solve my claim that the two calls behave differently
and should not!


>That's why I proposed adding a new variation of MultiCell() that accepts
the ln argument.

That's up to you.  The current api still lets me get my stuff done.  Thanks!


-Roger

**Comment by jung-kurt** [comment]
> Since that's the behavior is intended to match CellFormat wihen ln=1, could you please clarify that in
> https://godoc.org/github.com/jung-kurt/gofpdf#Fpdf.MultiCell?  

Will do -- thanks, Roger.
